/**
 *  Copyright 2012 Alma Madsen
 *
 *  BetaCreator is Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
(function() {function h(a){throw a;}var j=void 0,m=!0,n=null,r=!1;function aa(){return function(){}}var s,t=this;function ba(a,b){var c=a.split("."),d=t;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==j?d[e]=b:d=d[e]?d[e]:d[e]={}}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function da(a){return"array"==ca(a)}function u(a){return"string"==typeof a}function z(a){return"number"==typeof a}function ea(a){var b=typeof a;return"object"==b&&a!=n||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ha=0;function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){a||h(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ka;return A.apply(n,arguments)}
function la(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function B(a,b){function c(){}c.prototype=b.prototype;a.sc=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ma(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function na(a){if(!oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(pa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"&quot;"));return a}var pa=/&/g,qa=/</g,ra=/>/g,sa=/\"/g,oa=/[&<>\"]/,ta={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},ua={"'":"\\'"};var va,wa,xa,ya,za;function Aa(){return t.navigator?t.navigator.userAgent:n}function Ba(){return t.navigator}ya=xa=wa=va=r;var Ca;if(Ca=Aa()){var Da=Ba();va=0==Ca.indexOf("Opera");wa=!va&&-1!=Ca.indexOf("MSIE");xa=!va&&-1!=Ca.indexOf("WebKit");ya=!va&&!xa&&"Gecko"==Da.product}var Ea=va,C=wa,D=ya,E=xa,Fa=Ba();za=-1!=(Fa&&Fa.platform||"").indexOf("Mac");var Ga=!!Ba()&&-1!=(Ba().appVersion||"").indexOf("X11"),Ha;
a:{var Ia="",Ja;if(Ea&&t.opera)var Ka=t.opera.version,Ia="function"==typeof Ka?Ka():Ka;else if(D?Ja=/rv\:([^\);]+)(\)|;)/:C?Ja=/MSIE\s+([^\);]+)(\)|;)/:E&&(Ja=/WebKit\/(\S+)/),Ja)var La=Ja.exec(Aa()),Ia=La?La[1]:"";if(C){var Ma,Na=t.document;Ma=Na?Na.documentMode:j;if(Ma>parseFloat(Ia)){Ha=String(Ma);break a}}Ha=Ia}var Oa={};
function F(a){var b;if(!(b=Oa[a])){b=0;for(var c=ma(String(Ha)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",i=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var p=k.exec(g)||["","",""],q=l.exec(i)||["","",""];if(0==p[0].length&&0==q[0].length)break;b=((0==p[1].length?0:parseInt(p[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==p[1].length?0:parseInt(p[1],10))>(0==q[1].length?0:parseInt(q[1],10))?1:0)||((0==p[2].length)<
(0==q[2].length)?-1:(0==p[2].length)>(0==q[2].length)?1:0)||(p[2]<q[2]?-1:p[2]>q[2]?1:0)}while(0==b)}b=Oa[a]=0<=b}return b}var Pa={};function Qa(a){return Pa[a]||(Pa[a]=C&&!!document.documentMode&&document.documentMode>=a)};function Ra(a,b){for(var c in a)b.call(j,a[c],c,a)}var Sa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ta(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Sa.length;f++)c=Sa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var G=Array.prototype,Ua=G.indexOf?function(a,b,c){return G.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},H=G.forEach?function(a,b,c){G.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Va=G.filter?function(a,b,c){return G.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=u(a)?a.split(""):
a,i=0;i<d;i++)if(i in g){var k=g[i];b.call(c,k,i,a)&&(e[f++]=k)}return e},Wa=G.some?function(a,b,c){return G.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return m;return r};function Xa(a,b){var c=Ua(a,b);0<=c&&G.splice.call(a,c,1)}function Ya(a,b,c){return 2>=arguments.length?G.slice.call(a,b):G.slice.call(a,b,c)};function I(a,b,c){return Math.min(Math.max(a,b),c)};function J(a,b){this.x=a!==j?a:0;this.y=b!==j?b:0}J.prototype.clone=function(){return new J(this.x,this.y)};J.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Za(a,b){var c=a.x-b.x,d=a.y-b.y;return Math.sqrt(c*c+d*d)};function $a(a,b){this.width=a;this.height=b}s=$a.prototype;s.clone=function(){return new $a(this.width,this.height)};s.toString=function(){return"("+this.width+" x "+this.height+")"};s.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};s.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};s.scale=function(a){this.width*=a;this.height*=a;return this};var ab;function bb(a){a=a.className;return u(a)&&a.match(/\S+/g)||[]}function cb(a,b){for(var c=bb(a),d=Ya(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)0<=Ua(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e}function db(a,b){var c=bb(a),d=Ya(arguments,1),c=Va(c,function(a){return!(0<=Ua(d,a))});a.className=c.join(" ")};var eb=!C||Qa(9),fb=!D&&!C||C&&Qa(9)||D&&F("1.9.1");C&&F("9");function gb(a){return a?new hb(ib(a)):ab||(ab=new hb)}function jb(a,b){Ra(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in kb?a.setAttribute(kb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var kb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function lb(a,b,c){var d=arguments,e=document,f=d[0],g=d[1];if(!eb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',na(g.name),'"');if(g.type){f.push(' type="',na(g.type),'"');var i={};Ta(i,g);delete i.type;g=i}f.push(">");f=f.join("")}f=e.createElement(f);g&&(u(g)?f.className=g:da(g)?cb.apply(n,[f].concat(g)):jb(f,g));if(2<d.length)for(var k=e,l=f,e=function(a){a&&l.appendChild(u(a)?k.createTextNode(a):a)},g=2;g<d.length;g++){var p=d[g],i=ca(p);if(("array"==i||"object"==i&&"number"==typeof p.length)&&
!(ea(p)&&0<p.nodeType)){var q;a:{if(p&&"number"==typeof p.length){if(ea(p)){q="function"==typeof p.item||"string"==typeof p.item;break a}if("function"==ca(p)){q="function"==typeof p.item;break a}}q=r}i=H;if(q)if(q=p.length,0<q){for(var v=Array(q),y=0;y<q;y++)v[y]=p[y];p=v}else p=[];i(p,e)}else e(p)}return f}function mb(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function ib(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function nb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild(ib(a).createTextNode(b))}}function hb(a){this.Ka=a||t.document||document}hb.prototype.createElement=function(a){return this.Ka.createElement(a)};hb.prototype.createTextNode=function(a){return this.Ka.createTextNode(a)};hb.prototype.appendChild=function(a,b){a.appendChild(b)};function ob(a,b){u(b)?pb(a,j,b):Ra(b,la(pb,a))}function pb(a,b,c){a.style[String(c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})]=b}function qb(a,b){var c;a:{c=ib(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,n))){c=c[b]||c.getPropertyValue(b)||"";break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:n)||a.style&&a.style[b]}
function rb(a){var b=a.getBoundingClientRect();C&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function sb(a){if(C&&!Qa(8))return a.offsetParent;for(var b=ib(a),c=qb(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=qb(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return n}
function tb(a){var b,c=ib(a),d=qb(a,"position"),e=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new J(0,0),g;b=c?ib(c):document;if(g=C)if(g=!Qa(9))g="CSS1Compat"!=gb(b).Ka.compatMode;g=g?b.body:b.documentElement;if(a==g)return f;if(a.getBoundingClientRect)b=rb(a),c=gb(c).Ka,a=!E&&"CSS1Compat"==c.compatMode?c.documentElement:c.body,c=c.parentWindow||c.defaultView,a=new J(c.pageXOffset||a.scrollLeft,c.pageYOffset||a.scrollTop),
f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(E&&"fixed"==qb(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ea||E&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=sb(b))&&b!=c.body&&b!=g;)if(f.x-=b.scrollLeft,!Ea||"TR"!=b.tagName)f.y-=b.scrollTop}return f}
function ub(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}function vb(a){if("none"!=qb(a,"display"))return wb(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=wb(a);b.display=c;b.position=e;b.visibility=d;return a}function wb(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;return(b===j||d)&&a.getBoundingClientRect?(a=rb(a),new $a(a.right-a.left,a.bottom-a.top)):new $a(b,c)};function L(a){if(u(a)){var b=lb("SPAN");nb(b,a);return b}a.z=a.z||"DIV";var c=lb(a.z),d={id:a.id,"class":a.e,type:a.type,src:a.src,href:a.href,title:a.title,name:a.name,target:a.target,checked:a.checked,value:a.value},e={},f=r;for(b in d)d[b]!==j&&(e[b]=d[b],f=m);if(a.attr)for(b in a.attr)e[b]=a.attr[b],f=m;f&&jb(c,e);a.html&&(c.innerHTML=a.html);a.text&&nb(c,a.text);if(a.css)for(b in a.css)c.style[b]=a.css[b];if(a.children)for(b=0;b<a.children.length;b++)a.children[b]&&(d=L(a.children[b]),c.appendChild(d));
a.create&&a.create(c);a.click&&M(c,xb,function(b){a.click(b,c)});a.change&&M(c,yb,function(b){a.change(b,c)});return c};var zb;zb=function(){return m};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function Ab(a,b){var c=b||[];a&&c.push(a);return c}var Bb=E&&"BackCompat"==document.compatMode,Cb=document.firstChild.children?"children":"childNodes",Db=r;
function Eb(a){function b(){0<=l&&(x.id=c(l,w).replace(/\\/g,""),l=-1);if(0<=p){var a=p==w?n:c(p,w);0>">~+".indexOf(a)?x.z=a:x.hb=a;p=-1}0<=k&&(x.e.push(c(k+1,w).replace(/\\/g,"")),k=-1)}function c(b,c){return ma(a.slice(b,c))}for(var a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ",d=[],e=-1,f=-1,g=-1,i=-1,k=-1,l=-1,p=-1,q="",v="",y,w=0,ja=a.length,x=n,K=n;q=v,v=a.charAt(w),w<ja;w++)if("\\"!=q)if(x||(y=w,x={Fa:n,Ba:[],Wa:[],e:[],z:n,hb:n,id:n,Ab:function(){return Db?this.Nc:this.z}},p=w),0<=e)if("]"==
v){K.attr?K.Db=c(g||e+1,w):K.attr=c(e+1,w);if((e=K.Db)&&('"'==e.charAt(0)||"'"==e.charAt(0)))K.Db=e.slice(1,-1);x.Wa.push(K);K=n;e=g=-1}else"="==v&&(g=0<="|~^$*".indexOf(q)?q:"",K.type=g+v,K.attr=c(e+1,w-g.length),g=w+1);else 0<=f?")"==v&&(0<=i&&(K.value=c(f+1,w)),i=f=-1):"#"==v?(b(),l=w+1):"."==v?(b(),k=w):":"==v?(b(),i=w):"["==v?(b(),e=w,K={}):"("==v?(0<=i&&(K={name:c(i+1,w),value:n},x.Ba.push(K)),f=w):" "==v&&q!=v&&(b(),0<=i&&x.Ba.push({name:c(i+1,w)}),x.kc=x.Ba.length||x.Wa.length||x.e.length,
x.Sc=x.Fa=c(y,w),x.Nc=x.z=x.hb?n:x.z||"*",x.z&&(x.z=x.z.toUpperCase()),d.length&&d[d.length-1].hb&&(x.dc=d.pop(),x.Fa=x.dc.Fa+" "+x.Fa),d.push(x),x=n);return d}function Fb(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Gb(a){return 1==a.nodeType}function Hb(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(Db?a.getAttribute(b):a.getAttribute(b,2))||""}
var Ib={"*=":function(a,b){return function(c){return 0<=Hb(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==Hb(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+Hb(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+Hb(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+Hb(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return Hb(c,a)==b}}},Jb="undefined"==
typeof document.firstChild.nextElementSibling,Kb=!Jb?"nextElementSibling":"nextSibling",Lb=!Jb?"previousElementSibling":"previousSibling",Mb=Jb?Gb:zb;function Nb(a){for(;a=a[Lb];)if(Mb(a))return r;return m}function Ob(a){for(;a=a[Kb];)if(Mb(a))return r;return m}function Pb(a){var b=a.parentNode,c=0,d=b[Cb],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Kb])Mb(b)&&(b._i=++c,a===b&&(e=c));return e}
function Qb(a){return!(Pb(a)%2)}function Rb(a){return Pb(a)%2}
var Tb={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Nb},"last-child":function(){return Ob},"only-child":function(){return function(a){return!Nb(a)||!Ob(a)?r:m}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return r}return m}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=Eb(b)[0],d={$:1};"*"!=c.z&&(d.z=1);c.e.length||(d.e=1);var e=Sb(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return Rb;if("even"==b)return Qb;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=Pb(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var i=parseInt(b,10);return function(a){return Pb(a)==
i}}},Ub=C?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return Db?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Sb(a,b){if(!a)return zb;var b=b||{},c=n;b.$||(c=Fb(c,Gb));b.z||"*"!=a.z&&(c=Fb(c,function(b){return b&&b.tagName==a.Ab()}));b.e||H(a.e,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=Fb(c,function(a){return f.test(a.className)});c.count=b});b.Ba||H(a.Ba,function(a){var b=a.name;Tb[b]&&(c=Fb(c,Tb[b](b,a.value)))});b.Wa||H(a.Wa,function(a){var b,f=a.attr;a.type&&Ib[a.type]?b=Ib[a.type](f,a.Db):f.length&&(b=Ub(f));b&&(c=Fb(c,b))});b.id||a.id&&(c=Fb(c,function(b){return!!b&&b.id==a.id}));
c||"default"in b||(c=zb);return c}var Vb={};
function Wb(a){var b=Vb[a.Fa];if(b)return b;var c=a.dc,c=c?c.hb:"",d=Sb(a,{$:1}),e="*"==a.z,f=document.getElementsByClassName;if(c)if(f={$:1},e&&(f.z=1),d=Sb(a,f),"+"==c)var g=d,b=function(a,b,c){for(;a=a[Kb];)if(!Jb||Gb(a)){(!c||Xb(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var i=d,b=function(a,b,c){for(a=a[Kb];a;){if(Mb(a)){if(c&&!Xb(a,c))break;i(a)&&b.push(a)}a=a[Kb]}return b};else{if(">"==c)var k=d,k=k||zb,b=function(a,b,c){for(var d=0,e=a[Cb];a=e[d++];)Mb(a)&&((!c||Xb(a,c))&&k(a,d))&&
b.push(a);return b}}else if(a.id)d=!a.kc&&e?zb:Sb(a,{$:1,id:1}),b=function(b,c){var e;e=gb(b);var f=a.id;if(f=(e=u(f)?e.Ka.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return Ab(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.e.length&&!Bb)var d=Sb(a,{$:1,e:1,id:1}),l=a.e.join(" "),b=function(a,b){for(var c=Ab(0,b),e,f=0,g=a.getElementsByClassName(l);e=g[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.kc?b=function(b,c){for(var d=
Ab(0,c),e,f=0,g=b.getElementsByTagName(a.Ab());e=g[f++];)d.push(e);return d}:(d=Sb(a,{$:1,z:1,id:1}),b=function(b,c){for(var e=Ab(0,c),f,g=0,i=b.getElementsByTagName(a.Ab());f=i[g++];)d(f,b)&&e.push(f);return e});return Vb[a.Fa]=b}var Yb={},Zb={};
function $b(a){var b=Eb(ma(a));if(1==b.length){var c=Wb(b[0]);return function(a){if(a=c(a,[]))a.gb=m;return a}}return function(a){for(var a=Ab(a),c,f,g=b.length,i,k,l=0;l<g;l++){k=[];c=b[l];f=a.length-1;0<f&&(i={},k.gb=m);f=Wb(c);for(var p=0;c=a[p];p++)f(c,k,i);if(!k.length)break;a=k}return k}}var ac=!!document.querySelectorAll&&(!E||F("526"));
function bc(a,b){if(ac){var c=Zb[a];if(c&&!b)return c}if(c=Yb[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=m);if(ac&&!b&&-1==">~+".indexOf(c)&&(!C||-1==a.indexOf(":"))&&!(Bb&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Zb[a]=function(b){try{9==b.nodeType||d||h("");var c=b.querySelectorAll(e);C?c.Ac=m:c.gb=m;return c}catch(f){return bc(a,m)(b)}}}var f=a.split(/\s*,\s*/);return Yb[a]=
2>f.length?$b(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat($b(d)(a));return c}}var cc=0,dc=C?function(a){return Db?a.getAttribute("_uid")||a.setAttribute("_uid",++cc)||cc:a.uniqueID}:function(a){return a._uid||(a._uid=++cc)};function Xb(a,b){if(!b)return 1;var c=dc(a);return!b[c]?b[c]=1:0}
function ec(a){if(a&&a.gb)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;cc++;if(C&&Db){var c=cc+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(C&&a.Ac)try{for(d=1;e=a[d];d++)Gb(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=cc);for(d=1;e=a[d];d++)a[d]._zipIdx!=cc&&b.push(e),e._zipIdx=cc}return b}
function fc(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!u(a))return[a];if(u(b)&&(b=u(b)?document.getElementById(b):b,!b))return[];var b=b||document,c=b.ownerDocument||b.documentElement;Db=b.contentType&&"application/xml"==b.contentType||Ea&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(C?c.xml:b.xmlVersion||c.xmlVersion);return(c=bc(a)(b))&&c.gb?c:ec(c)}fc.Ba=Tb;ba("goog.dom.query",fc);ba("goog.dom.query.pseudos",fc.Ba);var gc={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function hc(a){var b={},a=String(a),c="#"==a.charAt(0)?a:"#"+a;if(ic.test(c))return b.I=jc(c),b.type="hex",b;a:{var d=a.match(kc);if(d){var c=Number(d[1]),e=Number(d[2]),d=Number(d[3]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=d&&255>=d){c=[c,e,d];break a}}c=[]}if(c.length)return b.I=lc(c),b.type="rgb",b;if(gc&&(c=gc[a.toLowerCase()]))return b.I=c,b.type="named",b;h(Error(a+" is not a valid color string"))}var mc=/#(.)(.)(.)/;
function jc(a){ic.test(a)||h(Error("'"+a+"' is not a valid hex color"));4==a.length&&(a=a.replace(mc,"#$1$1$2$2$3$3"));return a.toLowerCase()}function nc(a,b,c){a=Number(a);b=Number(b);c=Number(c);(isNaN(a)||0>a||255<a||isNaN(b)||0>b||255<b||isNaN(c)||0>c||255<c)&&h(Error('"('+a+","+b+","+c+'") is not a valid RGB color'));return"#"+oc(a.toString(16))+oc(b.toString(16))+oc(c.toString(16))}function lc(a){return nc(a[0],a[1],a[2])}
function pc(a,b,c){0>c?c+=1:1<c&&(c-=1);return 1>6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+6*(b-a)*(2/3-c):a}function qc(a,b,c){var d=0,e=0,f=0,a=a/360;if(0==b)d=e=f=255*c;else var g=f=0,g=0.5>c?c*(1+b):c+b-b*c,f=2*c-g,d=255*pc(f,g,a+1/3),e=255*pc(f,g,a),f=255*pc(f,g,a-1/3);return[Math.round(d),Math.round(e),Math.round(f)]}var ic=/^#(?:[0-9a-f]{3}){1,2}$/i,kc=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function oc(a){return 1==a.length?"0"+a:a};function rc(a){var b={},a=String(a),c="#"==a.charAt(0)?a:"#"+a;if(sc.test(c))return b.I=tc(c),b.type="hex",b;a:{var d=a.match(uc);if(d){var c=Number(d[1]),e=Number(d[2]),f=Number(d[3]),d=Number(d[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=f&&255>=f&&0<=d&&1>=d){c=[c,e,f,d];break a}}c=[]}if(c.length)return b.I=vc(c),b.type="rgba",b;a:{if(d=a.match(wc))if(c=Number(d[1]),e=Number(d[2]),f=Number(d[3]),d=Number(d[4]),0<=c&&360>=c&&0<=e&&100>=e&&0<=f&&100>=f&&0<=d&&1>=d){f=[c,e,f,d];break a}f=[]}if(f.length)return a=
f[0],c=f[1],e=f[2],f=f[3],d=Math.floor(255*f),(isNaN(d)||0>d||255<d)&&h(Error('"('+a+","+c+","+e+","+f+'") is not a valid HSLA color')),f=oc(d.toString(16)),a=lc(qc(a,c/100,e/100))+f,b.I=a,b.type="hsla",b;h(Error(a+" is not a valid color string"))}var xc=/#(.)(.)(.)(.)/;function tc(a){sc.test(a)||h(Error("'"+a+"' is not a valid alpha hex color"));5==a.length&&(a=a.replace(xc,"#$1$1$2$2$3$3$4$4"));return a.toLowerCase()}
function yc(a){a=tc(a);return[parseInt(a.substr(1,2),16),parseInt(a.substr(3,2),16),parseInt(a.substr(5,2),16),parseInt(a.substr(7,2),16)/255]}function vc(a){var b=a[0],c=a[1],d=a[2],a=a[3],e=Math.floor(255*a);(isNaN(e)||0>e||255<e)&&h(Error('"('+b+","+c+","+d+","+a+'") is not a valid RGBA color'));a=oc(e.toString(16));return nc(b,c,d)+a}var sc=/^#(?:[0-9a-f]{4}){1,2}$/i,uc=/^(?:rgba)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|1|0\.\d{0,10})\)$/i,wc=/^(?:hsla)\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\%,\s?(0|[1-9]\d{0,2})\%,\s?(0|1|0\.\d{0,10})\)$/i;function zc(a,b){b=b||"#ffffff";a=a||b;u(a)||h(Error(a+" is not a valid 6-hex color string"));7<a.length&&"#"==a[0]&&(a=a.substr(0,7));7<b.length&&"#"==b[0]&&(b=b.substr(0,7));try{return hc(a)}catch(c){return zc(b,"#ffffff")}}function Ac(a,b){b=b||"#ffffff";a=a||b;u(a)||h(Error(a+" is not a valid 8-hex color string"));try{return rc(a)}catch(c){try{var d=zc(a,b).I;return Ac(d+"ff",b+"ff")}catch(e){return Ac(b,"#ffffffff")}}}
function Bc(a){var b;b=0.5;for(var a=hc(a).I,a=jc(a),a=[parseInt(a.substr(1,2),16),parseInt(a.substr(3,2),16),parseInt(a.substr(5,2),16)],c=[[0,0,0],[255,255,255]],d=[],e=0;e<c.length;e++)d.push({color:c[e],Xb:Math.abs(Math.round((299*c[e][0]+587*c[e][1]+114*c[e][2])/1E3)-Math.round((299*a[0]+587*a[1]+114*a[2])/1E3))+(Math.abs(c[e][0]-a[0])+Math.abs(c[e][1]-a[1])+Math.abs(c[e][2]-a[2]))});d.sort(function(a,b){return b.Xb-a.Xb});a=d[0].color;return 1>b?(a.push(b),b=a[0],c=a[1],d=a[2],a=a[3],(isNaN(b)||
0>b||255<b||isNaN(c)||0>c||255<c||isNaN(d)||0>d||255<d||isNaN(a)||0>a||1<a)&&h(Error('"('+b+","+c+","+d+","+a+')" is not a valid RGBA color')),"rgba("+[b,c,d,a].join()+")"):lc(a)}
function N(a,b){this.Ec=m;this.da=this.U=this.V=this.W=0;!a&&b&&(a=b);a&&(u(a)?("transparent"==a.toLowerCase()&&(a="#0000"),Cc(this,a)):da(a)&&3<=a.length?Dc(this,[a[0],a[1],a[2],z(a[3])?a[3]:1]):a.Ec?this.clone(a):ea(a)&&("h"in a&&"s"in a&&"v"in a?Ec(this,[a.h,a.s,a.v,z(a.a)?a.a:1]):"h"in a&&"s"in a&&"l"in a?Fc(this,[a.h,a.s,a.l,z(a.a)?a.a:1]):"r"in a&&("g"in a&&"b"in a)&&Dc(this,[a.r,a.g,a.b,z(a.a)?a.a:1])))}N.prototype.clone=function(a){this.W=a.W;this.V=a.V;this.U=a.U;this.da=a.da;return this};
N.prototype.I=function(a){return a===j?lc(Gc(this)):Cc(this,a)};function Cc(a,b){if(b===j)return vc(Dc(a));var c=yc(Ac(b).I);a.W=c[0];a.V=c[1];a.U=c[2];a.da=c[3];return a}function Gc(a){return[a.W,a.V,a.U]}function Dc(a,b){if(b===j)return[a.W,a.V,a.U,a.da];a.W=I(Math.round(b[0]),0,255);a.V=I(Math.round(b[1]),0,255);a.U=I(Math.round(b[2]),0,255);a.da=I(z(b[3])?b[3]:1,0,1);return a}
function Fc(a,b){var c;if(b===j){c=a.W/255;var d=a.V/255,e=a.U/255,f=Math.max(c,d,e),g=Math.min(c,d,e),i=0,k=0,l=0.5*(f+g);f!=g&&(f==c?i=60*(d-e)/(f-g):f==d?i=60*(e-c)/(f-g)+120:f==e&&(i=60*(c-d)/(f-g)+240),k=0<l&&0.5>=l?(f-g)/(2*l):(f-g)/(2-2*l));c=[Math.round(i+360)%360,k,l]}else b===j?c=Fc(a).concat([a.da]):(d=I(Math.round(360+b[0])%360,0,360),e=I(b[1],0,1),f=I(b[2],0,1),c=I(z(b[3])?b[3]:1,0,1),d=qc(d,e,f),a.W=d[0],a.V=d[1],a.U=d[2],a.da=c,c=a);return c}
function Ec(a,b){if(b===j){var c,d=Gc(a);c=d[0];var e=d[1],f=d[2],d=Math.max(Math.max(c,e),f),g=Math.min(Math.min(c,e),f);if(g==d)g=c=0;else{var i=d-g,g=i/d;c=60*(c==d?(e-f)/i:e==d?2+(f-c)/i:4+(c-e)/i);0>c&&(c+=360);360<c&&(c-=360)}c=[c,g,d];c[0]=Fc(a)[0];c[2]/=255}else{var k=I(Math.round(360+b[0])%360,0,360),e=I(b[1],0,1),d=I(b[2],0,1);c=I(z(b[3])?b[3]:1,0,1);d=I(Math.round(255*d),0,255);i=g=f=0;if(0==e)i=g=f=d;else{var l=Math.floor(k/60),p=k/60-l,k=d*(1-e),q=d*(1-e*p),e=d*(1-e*(1-p));switch(l){case 1:f=
q;g=d;i=k;break;case 2:f=k;g=d;i=e;break;case 3:f=k;g=q;i=d;break;case 4:f=e;g=k;i=d;break;case 5:f=d;g=k;i=q;break;case 6:case 0:f=d,g=e,i=k}}e=[Math.floor(f),Math.floor(g),Math.floor(i)];a.W=e[0];a.V=e[1];a.U=e[2];a.da=c}}N.prototype.serialize=function(a){return a?{r:this.W,g:this.V,b:this.U,a:this.da}:Cc(this)};function Hc(){var a=this;this.sb=this.visible=r;this.Vc=n;this.Tc=[];this.Uc=12;this.pb=n;this.j=L({e:"callout hidden",children:[{e:"callout-bubble",create:function(b){a.Sb=b},children:[{e:"simple-color-picker",children:[{e:"preview-swatch",create:function(b){a.Hb=b}},{e:"input-container",children:[{z:"input",type:"text",e:"box-sizing-border",create:function(b){a.pc=b;M(b,Ic,function(){a.sb=m});M(b,Jc,function(){a.sb=r});M(b,Kc,function(a){a.stopPropagation()})},change:function(b,c){try{var d=new N(zc(c.value).I);
Lc(a,d)}catch(e){Mc(a,a.Ra)}}}]},{e:"button-container",children:[{z:"button",text:"Done",click:function(){(!a.X||a.X(a.Ra)!=r)&&a.hide()}}]},{e:"spacer"},{e:"swatch-container",create:function(b){a.pb=b}}]}]},{e:"callout-pointer-border"},{e:"callout-pointer"}]});M(this.Sb,Nc,function(a){a.stopPropagation()});M(this.Sb,Oc,function(){Pc(a,a.Sa);Mc(a,a.Ra)});this.Nb={};this.X=this.Ra=this.Sa=n;this.vb();Qc(O,Rc,function(){a.hide()})}
function Mc(a,b){b&&0<Dc(b)[3]?(db(a.Hb,"transparent"),a.Hb.style.backgroundColor=b.I(),a.sb||(a.pc.value=b.I())):(cb(a.Hb,"transparent"),a.sb||(a.pc.value="transparent"))}function Pc(a,b){H(fc(".selected",a.pb),function(a){db(a,"selected")});b&&cb(b,"selected")}function Lc(a,b){b?(a.Sa=a.Nb[b.I().toLowerCase()]||n,a.Ra=new N(b.I()),a.Sa&&Pc(a,a.Sa),Mc(a,b)):(a.Sa=n,a.Ra=n)}
Hc.prototype.vb=function(){var a;this.Nb={};var b=new N;for(a=0;12>a;a++)Ec(b,[0,0,(11-a)/11]),Sc(this,Gc(b));for(var c=0;9>c;c++)for(a=0;360>a;a+=30)Fc(b,[a,1,(9-c)/10]),Sc(this,Gc(b));a=L({e:"clear"});this.pb.appendChild(a)};
function Sc(a,b){var c=L({e:"swatch"+(b?"":" transparent"),css:{backgroundColor:b?"rgb("+Math.round(b[0])+","+Math.round(b[1])+","+Math.round(b[2])+")":"transparent"},create:function(c){var e=n;b&&(e=new N(b),a.Nb[e.I().toLowerCase()]=c);M(c,Tc,function(){Pc(a,c);Mc(a,e)});M(c,xb,function(){(!a.X||a.X(e)!==r)&&a.hide()})}});a.pb.appendChild(c)}
Hc.prototype.show=function(a,b,c,d){O.i(Rc);this.X=c;Lc(this,d);this.visible=m;this.j.style.display="block";var e;if(c=this.j.offsetParent)if(d="HTML"==c.tagName||"BODY"==c.tagName,!d||"static"!=qb(c,"position"))e=tb(c),d||(d=(d="rtl"==qb(c,"direction"))&&D?-c.scrollLeft:d&&(!C||!F("8"))?c.scrollWidth-c.clientWidth-c.scrollLeft:c.scrollLeft,c=new J(d,c.scrollTop),e=new J(e.x-c.x,e.y-c.y));e=e||new J;c=this.j;a-=e.x;d=b-e.y;e=D&&(za||Ga)&&F("1.9");a instanceof J?(b=a.x,a=a.y):(b=a,a=d);c.style.left=
ub(b,e);c.style.top=ub(a,e)};Hc.prototype.hide=function(){this.visible=r;this.j.style.display="none"};function Uc(){var a=this;this.visible=r;this.Ta=n;this.j=L({e:"text-area-container",children:[{e:"overlay"},{e:"wrapper",children:[{e:"heading",text:P("Edit Text Content")},{z:"textarea",create:function(b){a.Ta=b;M(b,Kc,function(a){a.stopPropagation()})}},{z:"button",e:"cancel",text:P("Cancel"),click:function(){a.hide()}},{z:"button",e:"save",text:P("Save"),click:function(){a.save()}}]}]});this.X=n}Uc.prototype.save=function(){(!this.X||this.X(this.Ta.value)!==r)&&this.hide()};
Uc.prototype.show=function(a,b){O.i(Rc);this.visible=m;this.X=a;this.Ta.value=b||"";this.j.style.display="block";setTimeout(A(function(){this.Ta.select&&this.Ta.select()},this),250)};Uc.prototype.hide=function(){this.visible=r;this.X=n;this.j.style.display="none"};function Vc(a,b,c,d){this.x=a;this.y=b;this.f=c;this.k=d}function Wc(a,b,c,d){if(2==arguments.length)return Math.sqrt(a*a+b*b);var e=c-a,f=d-b;return Math.sqrt(e*e+f*f)}function Xc(a,b,c,d,e,f,g){for(var i=0,k=a,l=b,p,q,v,y,g=g||6,w=1;w<=g;w++)p=w/g,v=1-p,q=v*v,v*=2*p,y=p*p,p=q*a+v*c+y*e,q=q*b+v*d+y*f,i+=Wc(k,l,p,q),k=p,l=q;return i}function Yc(a,b,c,d,e,f,g,i){if(0==g)return Zc(a,b,c,d,e,f,i);if(1==i)return $c(a,b,c,d,e,f,g);a=Zc(a,b,c,d,e,f,i);a.push(g/i);return $c.apply(n,a)}
function Zc(a,b,c,d,e,f,g){g=g||1;1!=g&&(e=c+(e-c)*g,f=d+(f-d)*g,c=a+(c-a)*g,d=b+(d-b)*g,e=c+(e-c)*g,f=d+(f-d)*g);return[a,b,c,d,e,f]}function $c(a,b,c,d,e,f,g){g=g||1;1!=g&&(a+=(c-a)*g,b+=(d-b)*g,c+=(e-c)*g,d+=(f-d)*g,a+=(c-a)*g,b+=(d-b)*g);return[a,b,c,d,e,f]}
function ad(a,b,c){var d=(c.x-b.x)*(c.x-b.x)+(c.y-b.y)*(c.y-b.y),e=((a.x-b.x)*(c.x-b.x)+(a.y-b.y)*(c.y-b.y))/d,d=Math.abs(((b.y-a.y)*(c.x-b.x)-(b.x-a.x)*(c.y-b.y))/d)*Math.sqrt(d);0<=e&&1>=e?a=d:(b=(a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y),a=(a.x-c.x)*(a.x-c.x)+(a.y-c.y)*(a.y-c.y),a=b<a?Math.sqrt(b):Math.sqrt(a));return a};function bd(a){this.$=a;this.e={};for(var a=this.$.className.split(" "),b=0,c=a.length;b<c;b++)this.e[a[b]]=m}function cd(a){var b=[],c;for(c in a.e)b.push(c);return b.join(" ")}bd.prototype.addClass=function(a){for(var a=a.split(" "),b=0,c=a.length;b<c;b++)this.e[a[b]]=m;this.$.className=cd(this)};bd.prototype.removeClass=function(a){for(var a=a.split(" "),b=0,c=a.length;b<c;b++)delete this.e[a[b]];this.$.className=cd(this)};function dd(a,b,c){function d(){if(!e.n){var a=parseFloat(e.input.value);z(a)&&(a/=e.oa);a:{for(var a=[a,e.Ia,e.value],b=a.length,c=0;c<b;c++)if(a[c]||0===a[c]||""===a[c]||a[c]===r){a=a[c];break a}a=n}e.O(a)}}var a=a||{},e=this;this.Yb=this.wc=this.input=n;this.j=L({e:"spinner",css:a.css||n,children:[{e:"spinner-textbox",children:[{z:"input",type:"text",create:function(a){e.input=a}}]},{e:"spinner-buttons",children:[{e:"spinner-up",create:function(a){e.wc=a},children:[{e:"icon-13 icon-13-spinner-arrows"}]},
{e:"spinner-down",create:function(a){e.Yb=a},children:[{e:"icon-13 icon-13-spinner-arrows"}]}]}]});this.Y=new bd(this.j);this.n=a.disabled||r;this.min=a.min||0;this.max=a.max===j?100:a.max;this.step=a.step||1;this.round=a.round||0;this.loop=!!a.loop;this.Mb=a.Mb||"";this.Ia=a.Ia||0;this.oa=a.oa||1;this.xb=a.xb===j?this.round:a.xb;this.value=0;this.ma=[];this.ac=[];this.Qb=[];this.O(a.value||this.Ia||0,m);a.change&&this.ma.push(a.change);a.focus&&this.ac.push(a.focus);a.blur&&this.Qb.push(a.blur);
b&&this.appendTo(b,c);M(this.input,yb,function(){d()});M(this.input,Kc,function(a){if(!e.n){var b=a.keyCode;38==b?(ed(e),a.preventDefault()):40==b?(fd(e),a.preventDefault()):13==b&&(d(),e.input.blur(),a.preventDefault());a.stopPropagation()}});M(this.input,Ic,function(){setTimeout(function(){e.input.select()},10);H(e.ac,function(a){a.call(e,e.value)})});M(this.input,Jc,function(){H(e.Qb,function(a){a.call(e)})});M(this.wc,xb,function(){e.n||ed(e)});M(this.Yb,xb,function(){e.n||fd(e)});this.n&&(this.n=
r,this.disable())}function ed(a){!z(a.value)&&a.bb!=n&&(a.value=a.bb);var b=(Math.round(a.oa*a.value/a.step)+1)*a.step/a.oa;a.loop&&b>a.max&&(b=a.min+(b-(a.max+1)));a.O(b)}function fd(a){!z(a.value)&&a.bb!=n&&(a.value=a.bb);var b=(Math.round(a.oa*a.value/a.step)-1)*a.step/a.oa;a.loop&&b<a.min&&(b=a.max+1-(a.min-b));a.O(b)}s=dd.prototype;
s.O=function(a,b){var c=r;if(a!==this.value||b)a=parseFloat(a),isNaN(a)?this.Ia!==n&&(this.value=this.Ia):(this.value=a>this.max?this.max:a<this.min?this.min:a,this.bb=this.value=1*this.value.toFixed(this.round)),this.ra(!!b),c=m;if(!b||c||""===this.input.value)this.input.value=u(this.value)?this.value:(this.value*this.oa).toFixed(this.xb||0).replace(/^([^\.]*)$/,"$1.").replace(/\.?0*$/,"")+this.Mb};s.ra=function(a){var b=this;H(this.ma,function(c){c.call(b,b.value,!!a)})};
s.appendTo=function(a,b){this.j.style.width=b?b+"px":"auto";a.appendChild(this.j);return this};s.Lb=function(a){if(this.n)return this;this.O(a,m);return this};s.focus=function(){this.input.focus();return this};s.blur=function(){this.input.blur();return this};s.enable=function(){this.n&&(this.Y.removeClass("disabled"),this.n=this.input.disabled=r);return this};s.disable=function(){this.n||(this.Y.addClass("disabled"),this.n=this.input.disabled=m);return this};function gd(a,b,c,d){b=b||{};this.Tb=a;this.j=L({e:"button-bar"+(b.e?" "+b.e:""),css:b.css||n});this.Y=new bd(this.j);this.n=b.disabled||r;this.value=[];this.ma=[];b.change&&this.ma.push(b.change);c&&this.appendTo(c,d);this.vb();this.n&&this.disable()}s=gd.prototype;s.O=function(a){this.value.push(a)};s.ra=function(a){var b=this;H(this.ma,function(c){c.call(b,b.value,!!a)})};s.appendTo=function(a,b){this.j.style.width=b?b+"px":"auto";a.appendChild(this.j);return this};
s.vb=function(){var a=this;this.value=[];H(this.Tb,function(b){var c=b.selected&&b.selected(),d=a.n||b.disabled&&b.disabled();c&&(b.value||0===b.value||b.value===r)&&a.O(b.value);c=L({e:"button-bar-item"+(c?" selected":"")+(d&&!a.n?" disabled":""),title:b.ca||n,click:function(){d=a.n||b.disabled&&b.disabled();d||(b.action(),a.refresh(m))},children:[{e:"icon-13 icon-13-"+b.aa}]});a.j.appendChild(c)})};
s.refresh=function(a){var b=this;this.value=[];H(this.Tb,function(a,d){var e=a.selected&&a.selected(),f=b.n||a.disabled&&a.disabled();e&&(a.value||0===a.value||a.value===r)&&b.O(a.value);(fb&&b.j.children!=j?b.j.children:Va(b.j.childNodes,function(a){return 1==a.nodeType}))[d].className="button-bar-item"+(e?" selected":"")+(f&&!b.n?" disabled":"")});this.ra(!a||r);return this};s.enable=function(){this.n&&(this.Y.removeClass("disabled"),this.n=r);return this.refresh()};
s.disable=function(){this.n||(this.Y.addClass("disabled"),this.n=m);return this.refresh()};function hd(a,b,c){var a=a||{},d=this;this.ob=this.tc=n;this.j=L({e:"color-well",children:[{e:"color-well-wrapper",children:[{e:"swatch-container",click:function(a,b){if(!d.n){var c=tb(b),i=vb(b);O.i(id,c.x+i.width/2,c.y+i.height+2,function(a){d.O(a)},d.value||n)}},children:[{e:"swatch",create:function(a){d.tc=a},children:[{z:"canvas",css:{position:"absolute"},create:function(a){d.ob=a}}]},{e:"border"}]}]}]});this.Y=new bd(this.j);this.n=a.disabled||r;this.value=a.value||new N("#fff");this.ma=[];
a.change&&this.ma.push(a.change);b&&this.appendTo(b,c);this.n&&this.disable()}s=hd.prototype;
s.ha=function(a){if(!this.Qc){var b=vb(this.tc);if(0==b.width&&!a)return;this.ob.width=b.width;this.ob.height=b.height;this.Qc=m}var a=this.ob.getContext("2d"),c=this.value;this.Y.removeClass("no-fill");this.n&&(c=new N("#ccccccff"));c||this.Y.addClass("no-fill");var b=a.canvas.width,d=a.canvas.height;a.clearRect(0,0,b,d);c&&(a.save(),c=Cc(c),c=yc(c),a.fillStyle="rgba("+c.join(",")+")",a.fillRect(0,0,b,d),a.restore())};s.O=function(a,b){this.value=a;this.ha();this.ra(!!b)};
s.ra=function(a){var b=this;H(this.ma,function(c){c.call(b,b.value,!!a)})};s.appendTo=function(a,b){this.j.style.width=b?b+"px":"";a.appendChild(this.j);return this};s.Lb=function(a){this.O(new N(a),m);return this};s.enable=function(){this.n&&(this.Y.removeClass("disabled"),this.n=r,this.ha());return this};s.disable=function(){this.n||(this.Y.addClass("disabled"),this.n=m,this.ha());return this};function jd(a,b){if(a==n)return n;b==n&&(b=0);if(100<b)return n;var c={};if("object"==typeof a){"undefined"!=typeof a.length&&(c=[]);for(var d in a){var e=typeof a[d];"object"==e?c[d]=a[d]instanceof HTMLElement?a[d]:jd(a[d],b+1):"string"==e?c[d]=a[d]:"number"==e?c[d]=a[d]:"function"==e?c[d]=a[d]:"boolean"==e?a[d]==m?c[d]=m:c[d]=r:"undefined"==e&&(c[d]=j)}}return c}
function kd(a,b){if("object"==typeof a&&"object"==typeof b){if(a==n&&b==n)return m;if(da(a)&&da(b)){if(a.length!=b.length)return r;for(var c=0;c<a.length;c++)if(!kd(a[c],b[c]))return r;return m}if(ea(a)&&ea(b)){for(c in a)if(!(c in(a.__proto__||a.constructor)||"__proto__"==c))if(!(c in b)||!kd(a[c],b[c]))return r;for(c in b)if(!(c in(b.__proto__||b.constructor)||"__proto__"==c)&&!(c in a))return r;return m}return r}return z(a)&&z(b)?1E-9>Math.abs(a-b):a==n&&b==n?m:a===b};function Q(a,b){this.type=a;this.q=b;this.Fb=n;this.Cb=this.Bb=r}Q.prototype.copy=function(){return new Q(this.type,jd(this.q))};function ld(a){var b=a.copy();switch(a.type){case 1:b.type=5;break;case 2:b.type=6;break;case 3:b.type=7;break;case 4:b.q=jd(a.Fb);break;case 5:b.type=1;break;case 6:b.type=2;break;case 7:b.type=3;break;default:return n}return b};var md=n;function nd(a,b){var c=md;if(c){var d=od(c);0<d.length?H(d,function(d){d.d[a]!==j&&(d={id:d.id},d[a]=b,R(c,new Q(4,d)))}):c.c.d[a]=b}}function pd(a){var b=md;b&&(b.Ha++,H(a,function(a){nd(a[0],a[1])}),qd(b))}function S(a){var b=md;if(b){var c=od(b),d;0<c.length?Wa(c,function(b){return b.d[a]!==j?(d=b.d[a],m):r}):d=b.c.d[a];return d}}function T(a,b){return function(c){c!==j&&a[b]!==j&&(a[b]=c);return a[b]}};function P(a){if(rd[a]){var b=a;return b="en"!=sd?rd[a][sd]||rd[a].en||a:rd[a].en||a}return a}var sd="en",rd={};function td(){function a(){return!z(S("fl"))}function b(){return!u(S("ta"))}function c(a,b,c,d){return new gd([{aa:a,action:function(){O.i(U,b,d)},ca:P(c),selected:function(){return g.mode==b&&(d===j||d==g.Ea)},disabled:function(){return r}}],n,ud(f))}function d(a){var b=[];H(a.wb,function(c){a.T?(c.action=function(){nd(a.T,c.val)},c.selected=function(){return S(a.T)==c.val},c.disabled=function(){return S(a.T)===j}):c.T&&(c.action=function(){nd(c.T,!S(c.T))},c.selected=function(){return!!S(c.T)},
c.disabled=function(){return S(c.T)===j});b.push(c)});return b}var e=this;this.j=lb("DIV","option-bar");this.viewport=lb("DIV","fullsize");this.j.appendChild(this.viewport);this.qc=[];this.Wc=n;var f=this.j,g=this,i=c("tool-select",vd,"Select Tool"),k=c("tool-line",wd,"Line Tool"),l=c("tool-anchor",V,"Anchor Tool",xd),p=c("tool-piton",V,"Piton Tool",yd),q=c("tool-rappel",V,"Rappel Tool",zd),v=c("tool-belay",V,"Belay Tool",Ad),y=c("tool-text",Bd,"Text Tool");Cd(f);var w=new hd({change:function(a,b){b||
nd("ic",a.I())}},ud(f));w.refresh=A(this.rc,this,w,"ic");Cd(f);var ja=L({e:"option-bar-label-left",text:"Scale:",children:n});f.appendChild(ja);ja=new dd({min:0.25,max:8,step:10,round:2,width:60,value:1,oa:100,Mb:"%",change:function(a,b){b||nd("is",a)}},ud(f),50);ja.refresh=A(this.rc,this,ja,"is");Cd(f);var x=new gd(d({wb:[{aa:"text-align-l",val:"l",ca:P("Left Align"),selected:function(){return"l"==S("ta")},disabled:b},{aa:"text-align-c",val:"c",ca:P("Center Align"),selected:function(){return"c"==
S("ta")},disabled:b},{aa:"text-align-r",val:"r",ca:P("Right Align"),selected:function(){return"r"==S("ta")},disabled:b}],T:"ta"}),n,ud(f)),K=new gd(d({wb:[{aa:"text-bg",T:"tb",ca:P("Toggle Text Background")}]}),n,ud(f));Cd(f);var Ee=new gd([{aa:"line-solid",action:function(){nd("fl",0)},ca:P("Solid Line"),selected:function(){return 0===S("fl")},disabled:a},{aa:"line-dashed",action:function(){pd([["fl",10],["nl",10]])},ca:P("Dashed Line"),selected:function(){return 2<S("nl")},disabled:a},{aa:"line-dotted",
action:function(){pd([["fl",8],["nl",0.01]])},ca:P("Dotted Line"),selected:function(){return 0<S("fl")&&2>=S("nl")},disabled:a}],n,ud(f)),Fe=new gd(d({wb:[{aa:"line-curved",T:"lc",ca:P("Toggle Line Curvature")}]}),n,ud(f)),Se=new gd([{aa:"line-edit",action:function(){O.i(U,Dd)},ca:P("Edit Line Shape"),selected:function(){return g.mode==Dd},disabled:a}],n,ud(f)),Te=[i,k,l,p,q,v,y,w,ja,x,K,Ee,Fe,Se];this.qc.push(function(){H(Te,function(a){a.refresh&&a.refresh()})});this.Ea=this.mode=n;Qc(O,U,function(a,
b){e.mode=a;e.Ea=b;e.refresh()})}td.prototype.ba=function(){Qc(O,Ed,A(this.refresh,this));Qc(O,Fd,A(this.refresh,this));O.i(U,vd)};function ud(a){var b=L({e:"option-bar-input"});a.appendChild(b);return b}function Cd(a){var b=L({e:"option-bar-divider"});a.appendChild(b)}td.prototype.rc=function(a,b){var c=S(b);c===j?(a.Lb(n),a.disable()):(a.enable(),a.Lb(c))};td.prototype.refresh=function(){H(this.qc,function(a){a()})};function Gd(a){var b=this;this.C=a;this.va=L({id:"betacreator",children:[{e:"fullsize viewport",create:function(a){b.viewport=a}},{e:"fullsize hitdiv",create:function(a){b.$a=a}},{e:"bc-gui",create:function(a){b.vc=a}},{create:function(a){b.Mc=a}}]});this.m=this.C.m;this.viewport.appendChild(this.m.view.j);this.oc=new td;this.vc.appendChild(this.oc.j);this.Wb=new Hc;this.vc.appendChild(this.Wb.j);Qc(O,id,function(a,d,e,f){b.Wb.show(a,d,e,f)});this.uc=new Uc;this.Mc.appendChild(this.uc.j);Qc(O,Hd,
function(a,d){b.uc.show(a,d)})}
Gd.prototype.ba=function(){var a=this;M(this.va,Nc,function(){O.i(Rc)});M(this.$a,Nc,function(b){a.m.qa(b)});M(this.$a,Id,function(b){a.m.ya(b)});M(this.$a,Jd,function(b){a.m.za(b)});M(this.$a,Kd,function(b){a.m.Za(b)});M(document,Kc,function(b){b.stopPropagation();if(!a.m.Ma(b)){var c=r;switch(b.keyCode){case 65:O.i(U,V,xd);break;case 66:O.i(U,V,Ad);break;case 76:O.i(U,wd);break;case 80:O.i(U,V,yd);break;case 82:O.i(U,V,zd);break;case 84:O.i(U,Bd);break;case 86:case 27:O.i(U,vd);break;case 89:if(b.ctrlKey||
b.metaKey)c=m,Ld(a.m);break;case 90:if(b.ctrlKey||b.metaKey)if(c=m,b.shiftKey)Ld(a.m);else{var d=a.m;if(0!==d.Ua.length){var e=[];H(d.Ua[0],function(a){a=ld(a);a!=n&&(a.Cb=m,a.Bb=r,e.unshift(a),R(d,a))});d.Ua.shift();d.Pa.unshift(e)}}break;case 8:case 46:c=m;a.m.Ha++;H(od(a.m),function(b){var c=n;b.Fc?(c=Md(b.d),c.id=b.id,R(a.m,new Q(5,c))):b.p?(c=Nd(b.d),c.id=b.id,R(a.m,new Q(6,c))):b.Gc&&(c=Od(b.d),c.id=b.id,R(a.m,new Q(7,c)))});qd(a.m);a.m.selected=n;O.i(Ed);O.i(W);break;case 189:if(b.ctrlKey||
b.metaKey)c=m,a.m.Pb();break;case 187:if(b.ctrlKey||b.metaKey)c=m,a.m.Ob()}c&&b.preventDefault()}});this.oc.ba()};function Pd(){0!=Qd&&(this.Rc=Error().stack,fa(this))}var Qd=0;function Rd(){Pd.call(this);this.ja=[];this.qb={}}B(Rd,Pd);Rd.prototype.gc=1;Rd.prototype.kb=0;function Qc(a,b,c){var d=a.qb[b];d||(d=a.qb[b]=[]);var e=a.gc;a.ja[e]=b;a.ja[e+1]=c;a.ja[e+2]=j;a.gc=e+3;d.push(e)}
Rd.prototype.i=function(a,b){var c=this.qb[a];if(c){this.kb++;for(var d=Ya(arguments,1),e=0,f=c.length;e<f;e++){var g=c[e];this.ja[g+1].apply(this.ja[g+2],d)}this.kb--;if(this.ib&&0==this.kb)for(;c=this.ib.pop();)if(0!=this.kb)this.ib||(this.ib=[]),this.ib.push(c);else if(d=this.ja[c])(d=this.qb[d])&&Xa(d,c),delete this.ja[c],delete this.ja[c+1],delete this.ja[c+2]}};function Sd(){}var Td=0;s=Sd.prototype;s.key=0;s.Ga=r;s.Ub=r;s.ba=function(a,b,c,d,e,f){"function"==ca(a)?this.ec=m:a&&a.handleEvent&&"function"==ca(a.handleEvent)?this.ec=r:h(Error("Invalid listener argument"));this.cb=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.bc=f;this.Ub=r;this.key=++Td;this.Ga=r};s.handleEvent=function(a){return this.ec?this.cb.call(this.bc||this.src,a):this.cb.handleEvent.call(this.cb,a)};!C||Qa(9);var Ud=!C||Qa(9),Vd=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||Ea&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");var xb="click",Kd="dblclick",Nc="mousedown",Jd="mouseup",Tc="mouseover",Oc="mouseout",Id="mousemove",Kc="keydown",Jc="blur",Ic="focus",yb="change";function Wd(a,b){this.type=a;this.currentTarget=this.target=b}s=Wd.prototype;s.jb=r;s.defaultPrevented=r;s.Pc=m;s.stopPropagation=function(){this.jb=m};s.preventDefault=function(){this.defaultPrevented=m;this.Pc=r};function Xd(a){Xd[" "](a);return a}Xd[" "]=aa();function Yd(a,b){a&&this.ba(a,b)}B(Yd,Wd);s=Yd.prototype;s.target=n;s.relatedTarget=n;s.offsetX=0;s.offsetY=0;s.clientX=0;s.clientY=0;s.screenX=0;s.screenY=0;s.button=0;s.keyCode=0;s.charCode=0;s.ctrlKey=r;s.altKey=r;s.shiftKey=r;s.metaKey=r;s.Oc=r;s.La=n;
s.ba=function(a,b){var c=this.type=a.type;Wd.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(D){var e;a:{try{Xd(d.nodeName);e=m;break a}catch(f){}e=r}e||(d=n)}}else c==Tc?d=a.fromElement:c==Oc&&(d=a.toElement);this.relatedTarget=d;this.offsetX=E||a.offsetX!==j?a.offsetX:a.layerX;this.offsetY=E||a.offsetY!==j?a.offsetY:a.layerY;this.clientX=a.clientX!==j?a.clientX:a.pageX;this.clientY=a.clientY!==j?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Oc=za?a.metaKey:a.ctrlKey;this.state=a.state;this.La=a;a.defaultPrevented&&this.preventDefault();delete this.jb};s.stopPropagation=function(){Yd.sc.stopPropagation.call(this);this.La.stopPropagation?this.La.stopPropagation():this.La.cancelBubble=m};
s.preventDefault=function(){Yd.sc.preventDefault.call(this);var a=this.La;if(a.preventDefault)a.preventDefault();else if(a.returnValue=r,Vd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Zd={},X={},$d={},ae={};
function M(a,b,c,d,e){if(b){if(da(b)){for(var f=0;f<b.length;f++)M(a,b[f],c,d,e);return n}var d=!!d,g=X;b in g||(g[b]={ea:0,Ca:0});g=g[b];d in g||(g[d]={ea:0,Ca:0},g.ea++);var g=g[d],i=fa(a),k;g.Ca++;if(g[i]){k=g[i];for(f=0;f<k.length;f++)if(g=k[f],g.cb==c&&g.bc==e){if(g.Ga)break;return k[f].key}}else k=g[i]=[],g.ea++;var l=be,p=Ud?function(a){return l.call(p.src,p.key,a)}:function(a){a=l.call(p.src,p.key,a);if(!a)return a},f=p;f.src=a;g=new Sd;g.ba(c,f,a,b,d,e);c=g.key;f.key=c;k.push(g);Zd[c]=g;
$d[i]||($d[i]=[]);$d[i].push(g);a.addEventListener?(a==t||!a.Bc)&&a.addEventListener(b,f,d):a.attachEvent(b in ae?ae[b]:ae[b]="on"+b,f);return c}h(Error("Invalid event type"))}
function ce(a){if(Zd[a]){var b=Zd[a];if(!b.Ga){var c=b.src,d=b.type,e=b.proxy,f=b.capture;c.removeEventListener?(c==t||!c.Bc)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in ae?ae[d]:ae[d]="on"+d,e);c=fa(c);$d[c]&&(e=$d[c],Xa(e,b),0==e.length&&delete $d[c]);b.Ga=m;if(b=X[d][f][c])b.nc=m,de(d,f,c,b);delete Zd[a]}}}
function de(a,b,c,d){if(!d.eb&&d.nc){for(var e=0,f=0;e<d.length;e++)d[e].Ga?d[e].proxy.src=n:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.nc=r;0==f&&(delete X[a][b][c],X[a][b].ea--,0==X[a][b].ea&&(delete X[a][b],X[a].ea--),0==X[a].ea&&delete X[a])}}function ee(a,b,c,d,e){var f=1,b=fa(b);if(a[b]){a.Ca--;a=a[b];a.eb?a.eb++:a.eb=1;try{for(var g=a.length,i=0;i<g;i++){var k=a[i];k&&!k.Ga&&(f&=fe(k,e)!==r)}}finally{a.eb--,de(c,d,b,a)}}return Boolean(f)}function fe(a,b){a.Ub&&ce(a.key);return a.handleEvent(b)}
function be(a,b){if(!Zd[a])return m;var c=Zd[a],d=c.type,e=X;if(!(d in e))return m;var e=e[d],f,g;if(!Ud){var i;if(!(i=b))a:{i=["window","event"];for(var k=t;f=i.shift();)if(k[f]!=n)k=k[f];else{i=n;break a}i=k}f=i;i=m in e;k=r in e;if(i){if(0>f.keyCode||f.returnValue!=j)return m;a:{var l=r;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(p){l=m}if(l||f.returnValue==j)f.returnValue=m}}l=new Yd;l.ba(f,this);f=m;try{if(i){for(var q=[],v=l.currentTarget;v;v=v.parentNode)q.push(v);g=e[m];g.Ca=g.ea;for(var y=
q.length-1;!l.jb&&0<=y&&g.Ca;y--)l.currentTarget=q[y],f&=ee(g,q[y],d,m,l);if(k){g=e[r];g.Ca=g.ea;for(y=0;!l.jb&&y<q.length&&g.Ca;y++)l.currentTarget=q[y],f&=ee(g,q[y],d,r,l)}}else f=fe(c,l)}finally{q&&(q.length=0)}return f}d=new Yd(b,this);return f=fe(c,d)};var xd=1,yd=2,zd=3,Ad=4;function ge(a){if(a)return he[a]=m,a;a="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)});return he[a]?ge():ge(a)}var he={};function ie(a,b){a=a||{};this.Fc=m;this.id=ge(a.id);this.d={};this.d.it=n;this.d.is=a.scale||b.is;this.d.ic=a.color||b.ic;this.d.ia=a.alpha||b.ia;this.d.lw=a.lineWidth||3;this.d.x=a.x||0;this.d.y=a.y||0;this.d.w=a.f||18;this.d.h=a.k||18;this.d.t=a.text||"";this.type=T(this.d,"it");this.scale=T(this.d,"is");this.color=T(this.d,"ic");this.alpha=T(this.d,"ia");this.lineWidth=T(this.d,"lw");this.x=T(this.d,"x");this.y=T(this.d,"y");this.f=T(this.d,"w");this.k=T(this.d,"h");this.text=T(this.d,"t");this.la=
"is ic ia x y w h t".split(" ");this.offset=new J(0,0)}s=ie.prototype;s.ub=function(){var a={};a.x=this.x()+this.offset.x;a.y=this.y()+this.offset.y;this.offset.x=0;this.offset.y=0;return a};function Md(a){a=a||{};return{type:a.it,scale:a.is,color:a.ic,alpha:a.ia,lineWidth:a.lw,x:a.x,y:a.y,f:a.w,k:a.h,text:a.t}}s.Kb=function(a){this.offset.x=a.x;this.offset.y=a.y};s.mb=function(){var a={},b;for(b in this.d)a[b]=this.d[b];return a};
s.yb=function(){var a=this,b={};H(this.la,function(c){b[c]=a.d[c]});return b};s.Jb=function(a){var b=this;H(this.la,function(c){a[c]!==j&&(b.d[c]=a[c])})};function je(a,b){a=a||{};a.f||(a.f=10);a.k||(a.k=10);ie.call(this,a,b);this.type(xd)}B(je,ie);je.prototype.ga=function(a,b){var c=this.scale(),d=this.f()*c,e=this.k()*c,c=this.lineWidth()*c/2+6;return ad(new J(a,b),new J(this.x()-d/2,this.y()-e/2),new J(this.x()+d/2,this.y()+e/2))<c||ad(new J(a,b),new J(this.x()+d/2,this.y()-e/2),new J(this.x()-d/2,this.y()+e/2))<c?m:r};function Y(a,b){this.canvas=a;this.id=b}s=Y.prototype;s.qa=aa();s.ya=aa();s.za=aa();s.Za=aa();s.Ma=aa();function ke(a,b){Y.call(this,a,b);this.xc=this.mc=this.F=n}B(ke,Y);function le(a){var b=a.canvas;b.offset.x+=b.hc||0;b.offset.y+=b.jc||0;b.hc=0;b.jc=0;ce(a.mc);ce(a.xc)}s=ke.prototype;s.Oa=function(){this.F=n};
s.qa=function(a,b){var c=this,d=m;this.F&&this.za(a,b);this.F=b;me(this.canvas.c,function(a){if(a.ga(b.x,b.y,c.canvas.selected==a.id))return c.canvas.selected=a.id,O.i(Ed),O.i(W),d=r,m});if(d){this.canvas.selected=n;O.i(Ed);O.i(W);var e=this;le(this);var f=this.canvas,g=Math.round(f.c.f*f.c.scale),i=Math.round(f.c.k*f.c.scale);f.Kc=-Math.max(f.offset.x+g-f.C.H,0);f.Ic=Math.max(-f.offset.x,0);f.Lc=-Math.max(f.offset.y+i-f.C.L,0);f.Jc=Math.max(-f.offset.y,0);var k=a.clientX,l=a.clientY;this.mc=M(document.body,
Id,function(a){var b=e.canvas,c=a.clientX-k,a=a.clientY-l,c=I(c,b.Kc,b.Ic),a=I(a,b.Lc,b.Jc);b.hc=c;b.jc=a;b.view.j.style.left=b.offset.x+c+"px";b.view.j.style.top=b.offset.y+a+"px"});this.xc=M(document.body,Jd,function(){le(e)})}};s.ya=function(a,b){var c=this;this.F&&(H(od(this.canvas),function(a){a.Kb(new J(b.x-c.F.x,b.y-c.F.y))}),O.i(W))};
s.za=function(a,b){var c=this;if(this.F){var d=b.x-this.F.x,e=b.y-this.F.y;(2<Math.abs(d)||2<Math.abs(e))&&H(od(this.canvas),function(a){var b=a.ub(new J(d,e));b.id=a.id;R(c.canvas,new Q(4,b))})}this.F=n};
s.Za=function(a,b){var c=this;me(this.canvas.c,function(a){if(0==a.type()&&a.ga(b.x,b.y,c.canvas.selected==a.id))return O.i(U,Dd),m;if(a.type()==Ad&&a.ga(b.x,b.y,c.canvas.selected==a.id)){var e=prompt(P("Enter text for the belay:"),a.text());if(e!==n&&e!=a.text()){var f={id:a.id};f.t=e;R(c.canvas,new Q(4,f))}return m}if(5==a.type()&&a.ga(b.x,b.y,c.canvas.selected==a.id))return O.i(Hd,function(b){if(b!==n&&b!=a.text()){var e={id:a.id};e.t=b;R(c.canvas,new Q(4,e))}},a.text()),m})};function ne(a,b){a=a||{};a.f||(a.f=12);a.k||(a.k=12);ie.call(this,a,b);this.type(yd)}B(ne,ie);ne.prototype.ga=function(a,b){var c=this.lineWidth()*this.scale()/2+1,d=this.f()*this.scale(),e=this.k()*this.scale();if(Math.abs(a-this.x())>d/2+c||Math.abs(b-this.y())>e/2+c)return r;d=this.x()-0.1*d;e=this.y()+0.1*e;return a<d-c||a>d+c&&b>e+c?r:m};function oe(a,b,c){this.xa=a;this.yc=6;this.p=m;this.Ya=this.A=this.u=this.overflow=0;this.o=n;this.A=b;this.u=c;this.Ya=this.A+this.u;this.p=m;this.overflow=0;this.o={x:0,y:0}}s=oe.prototype;s.moveTo=function(a,b){Z(this,a,b)};
s.lineTo=function(a,b){var c=a-this.o.x,d=b-this.o.y,e=Math.atan2(d,c),f=Math.cos(e),e=Math.sin(e),c=Wc(0,0,c,d);if(this.overflow){if(this.overflow>c){this.p?pe(this,a,b):Z(this,a,b);this.overflow-=c;return}this.p?pe(this,this.o.x+f*this.overflow,this.o.y+e*this.overflow):Z(this,this.o.x+f*this.overflow,this.o.y+e*this.overflow);c-=this.overflow;this.overflow=0;this.p=!this.p;if(!c)return}if(d=Math.floor(c/this.Ya)){for(var g=f*this.A,i=e*this.A,k=f*this.u,l=e*this.u,p=0;p<d;p++)this.p?(pe(this,this.o.x+
g,this.o.y+i),Z(this,this.o.x+k,this.o.y+l)):(Z(this,this.o.x+k,this.o.y+l),pe(this,this.o.x+g,this.o.y+i));c-=this.Ya*d}this.p?c>this.A?(pe(this,this.o.x+f*this.A,this.o.y+e*this.A),Z(this,a,b),this.overflow=this.u-(c-this.A),this.p=r):(pe(this,a,b),c==this.A?(this.overflow=0,this.p=!this.p):(this.overflow=this.A-c,Z(this,a,b))):c>this.u?(Z(this,this.o.x+f*this.u,this.o.y+e*this.u),pe(this,a,b),this.overflow=this.A-(c-this.u),this.p=m):(Z(this,a,b),c==this.u?(this.overflow=0,this.p=!this.p):this.overflow=
this.u-c)};
s.quadraticCurveTo=function(a,b,c,d){var e=this.o.x,f=this.o.y,g=Xc(e,f,a,b,c,d,this.yc),i=0,k=0,l;if(this.overflow){if(this.overflow>g){this.p?qe(this,a,b,c,d):Z(this,c,d);this.overflow-=g;return}i=this.overflow/g;l=Zc(e,f,a,b,c,d,i);this.p?qe(this,l[2],l[3],l[4],l[5]):Z(this,l[4],l[5]);this.overflow=0;this.p=!this.p;if(!g)return}var p;p=Math.floor((g-g*i)/this.Ya);var q=this.A/g,v=this.u/g;if(p)for(var y=0;y<p;y++)this.p?(k=i+q,l=Yc(e,f,a,b,c,d,i,k),qe(this,l[2],l[3],l[4],l[5]),i=k,k=i+v,l=Yc(e,
f,a,b,c,d,i,k),Z(this,l[4],l[5])):(k=i+v,l=Yc(e,f,a,b,c,d,i,k),Z(this,l[4],l[5]),i=k,k=i+q,l=Yc(e,f,a,b,c,d,i,k),qe(this,l[2],l[3],l[4],l[5])),i=k;p=g-g*i;this.p?p>this.A?(l=Yc(e,f,a,b,c,d,i,i+q),qe(this,l[2],l[3],l[4],l[5]),Z(this,c,d),this.overflow=this.u-(p-this.A),this.p=r):(l=$c(e,f,a,b,c,d,i),qe(this,l[2],l[3],l[4],l[5]),g==this.A?(this.overflow=0,this.p=!this.p):(this.overflow=this.A-p,Z(this,c,d))):p>this.u?(k=i+v,l=Yc(e,f,a,b,c,d,i,k),Z(this,l[4],l[5]),l=$c(e,f,a,b,c,d,k),qe(this,l[2],l[3],
l[4],l[5]),this.overflow=this.A-(p-this.u),this.p=m):(Z(this,c,d),p==this.u?(this.overflow=0,this.p=!this.p):this.overflow=this.u-p)};s.beginPath=function(){this.xa.beginPath()};s.stroke=function(){this.xa.stroke()};s.clearRect=function(a,b,c,d){this.xa.clearRect(a,b,c,d)};s.Ja=function(){this.o=this.xa=n};function Z(a,b,c){a.o={x:b,y:c};a.xa.moveTo(b,c)}function pe(a,b,c){b==a.o.x&&c==a.o.y||(a.o={x:b,y:c},a.xa.lineTo(b,c))}
function qe(a,b,c,d,e){b==d&&c==e&&d==a.o.x&&e==a.o.y||(a.o={x:d,y:e},a.xa.quadraticCurveTo(b,c,d,e))};function re(a,b){a=a||{};this.p=m;this.id=ge(a.id);this.d={};this.d.it=0;this.d.is=a.scale||b.is;this.d.ic=a.color||b.ic;this.d.ia=a.alpha||b.ia;this.d.lw=a.lineWidth||3;this.d.cp=a.D||[];this.d.nl=a.A||b.nl;this.d.fl=z(a.u)?a.u:b.fl;this.d.lc=a.Xa||b.lc;this.type=T(this.d,"it");this.scale=T(this.d,"is");this.color=T(this.d,"ic");this.alpha=T(this.d,"ia");this.lineWidth=T(this.d,"lw");this.D=T(this.d,"cp");this.A=T(this.d,"nl");this.u=T(this.d,"fl");this.Xa=T(this.d,"lc");this.la="is ic ia lw cp nl fl lc".split(" ");
this.offset=new J(0,0);this.sa=[];se(this)}function te(a,b,c,d,e,f){var g=[],i=Xc(a,b,c,d,e,f),k=0,l=0,p=Math.floor(i/10),i=10/i;if(p){for(var q=0;q<p;q++)l=k+i,k=Yc(a,b,c,d,e,f,k,l),g.push(new J(k[4],k[5])),k=l;g.push(new J(e,f))}return g}s=re.prototype;s.ub=function(){var a=this,b=[],c={};H(this.D(),function(c){b.push(new J(c.x+a.offset.x,c.y+a.offset.y))});this.offset.x=0;this.offset.y=0;c.cp=b;return c};
function Nd(a){var a=a||{},b={type:a.it,scale:a.is,color:a.ic,alpha:a.ia,lineWidth:a.lw,A:a.nl,u:a.fl,Xa:a.lc};if(a.cp&&da(a.cp)){var c=[];H(a.cp,function(a){c.push(new J(a.x,a.y))});b.D=c}return b}s.Kb=function(a){this.offset=a};s.mb=function(){var a={},b;for(b in this.d)a[b]=this.d[b];if(a.cp&&da(a.cp)){var c=[];H(a.cp,function(a){c.push({x:a.x,y:a.y})});a.cp=c}return a};s.yb=function(){var a=this,b={};H(this.la,function(c){b[c]=a.d[c]});return b};
s.Jb=function(a){var b=this;H(this.la,function(c){a[c]!==j&&(b.d[c]=a[c])})};s.ga=function(a,b){for(var c=this.sa,d=this.lineWidth()*this.scale()/2+6,e=0,f=c.length-1;e<f;e++)if(ad(new J(a,b),c[e],c[e+1])<d)return m;return r};
function se(a){var b=[];if(a.Xa()){var c=a.D(),d=c.length;H(c,function(a,f){if(0===f)b.push(new J(a.x,a.y));else{var g=c[f-1];1==f?b.push(new J((a.x+g.x)/2,(a.y+g.y)/2)):b=b.concat(te(b[b.length-1].x,b[b.length-1].y,g.x,g.y,(a.x+g.x)/2,(a.y+g.y)/2));f==d-1&&b.push(new J(a.x,a.y))}})}else H(a.D(),function(a){b.push(new J(a.x,a.y))});a.sa=b};function ue(a,b,c){Y.call(this,a,b);this.sa=[];this.K=this.B=this.Na=n;this.zc=c}B(ue,Y);ue.prototype.qa=function(a,b){this.B&&this.B.D(ve(this));this.sa.push(new J(b.x,b.y));if(this.B){var c={id:this.B.id};c.cp=ve(this);R(this.canvas,new Q(4,c))}else 1<this.sa.length?(we(this),c=new Q(2,{D:ve(this)}),R(this.canvas,c),this.B=this.canvas.c.getItem(c.q.id)):(this.Na=new J(b.x,b.y),this.K=this.zc,this.K.D(ve(this,this.Na)),this.K.A(this.canvas.c.d.nl),this.K.u(this.canvas.c.d.fl),O.i(W))};
ue.prototype.ya=function(a,b){var c=this.B||this.K;c&&(this.Na=new J(b.x,b.y),c.D(ve(this,this.Na)),se(c),O.i(W))};ue.prototype.Ma=function(a){if(13==a.keyCode&&this.B)return this.Oa(),m};ue.prototype.Oa=function(){this.B&&(this.B.D(ve(this)),se(this.B),O.i(W));this.sa=[];this.B=this.Na=n;we(this)};function ve(a,b){return b?a.sa.concat([b]):a.sa.concat([])}function we(a){a.K&&a.K.D([new J(0,0)]);a.K=n};function xe(a,b){a=a||{};a.lineWidth||(a.lineWidth=2);ie.call(this,a,b);this.type(Ad)}B(xe,ie);xe.prototype.ga=function(a,b){var c=this.lineWidth()*this.scale()/2+1;return Za(new J(a,b),new J(this.x(),this.y()))<=this.f()*this.scale()/2+c?m:r};function ye(a){this.c=a;this.padding=this.na=10;this.S=this.R=n;this.canvas=document.createElement("CANVAS");this.canvas.width=this.c.f()+2*this.padding;this.canvas.height=this.c.k()+2*this.padding;this.canvas.style.position="absolute"}s=ye.prototype;s.N=aa();
s.Va=function(a){var a=a||1,b=a*this.c.scale(),c=Math.round(b*this.c.f())+2*this.padding,b=Math.round(b*this.c.k())+2*this.padding;this.canvas.style.left=Math.round(a*(this.c.x()+this.c.offset.x)-c/2)+"px";this.canvas.style.top=Math.round(a*(this.c.y()+this.c.offset.y)-b/2)+"px"};
s.ka=function(a,b,c,d){this.padding=this.na*Math.max(1,b);var e=Math.round(b*this.c.f())+2*this.padding,f=Math.round(b*this.c.k())+2*this.padding;d||(a.canvas.width=e,a.canvas.height=f,a.clearRect(0,0,e,f));a.save();d&&a.translate(Math.round(this.c.x()-e/2),Math.round(this.c.y()-f/2));a.translate(this.padding,this.padding);a.scale(b,b);a.lineCap="round";c&&(a.save(),this.N(a,"rgba(255,0,0,0.75)",this.c.lineWidth()+4/b),a.restore());a.save();this.N(a,Bc(this.c.color()),this.c.lineWidth()+2/b);a.restore();
this.N(a);a.restore()};s.ha=function(a,b){var a=a||1,c=a*this.c.scale(),d={f:this.c.f(),k:this.c.k(),color:this.c.color(),alpha:this.c.alpha(),scale:c,selected:b,text:this.c.text()},e={x:this.c.x(),y:this.c.y(),f:this.c.f(),k:this.c.k(),Zb:this.c.offset.x,$b:this.c.offset.y,scale:c};kd(d,this.R)||(this.R=d,d=this.canvas.getContext("2d"),this.ka(d,c,b));kd(e,this.S)||(this.S=e,this.Va(a))};s.Qa=function(a){a.save();this.ka(a,this.c.scale(),r,m);a.restore()};
s.Ja=function(){this.S=this.R=this.c=n;mb(this.canvas);this.canvas=n};function ze(a,b){a=a||{};a.lineWidth||(a.lineWidth=2);ie.call(this,a,b);this.type(zd)}B(ze,ie);ze.prototype.ga=function(a,b){var c=this.lineWidth()*this.scale()/2+1;return Za(new J(a,b),new J(this.x(),this.y()))<=this.f()*this.scale()/2+c?m:r};function Ae(a){ye.call(this,a);this.c=a}B(Ae,ye);Ae.prototype.N=function(a,b,c){a.strokeStyle=b||this.c.color();a.lineWidth=c||this.c.lineWidth();a.beginPath();var b=this.c.f(),c=this.c.k(),d=Math.min(this.c.f(),this.c.k())/2;a.moveTo(b/2+d*Math.cos(0),c/2+d*Math.sin(0));a.arc(b/2,c/2,d,0,2*Math.PI,r);a.moveTo(b/2,0.25*c);a.lineTo(b/2,0.75*c);a.moveTo(0.25*b,c/2);a.lineTo(b/2,0.75*c);a.lineTo(0.75*b,c/2);a.stroke()};function Be(a){ye.call(this,a);this.c=a}B(Be,ye);Be.prototype.N=function(a,b,c){var d=this.c.f(),e=this.c.k(),f=0.3*e;a.strokeStyle=b||this.c.color();a.lineWidth=c||this.c.lineWidth();a.beginPath();a.moveTo(0.4*d,e);a.lineTo(0.4*d,0);a.lineTo(d-f,0);a.arc(d-f,f,f,-Math.PI/2,Math.PI/2,r);a.lineTo(0.4*d,2*f);a.stroke()};function Ce(a,b){a=a||{};this.Gc=m;this.id=ge(a.id);this.d={};this.d.it=5;this.d.is=a.scale||b.is;this.d.ic=a.color||b.ic;this.d.ia=a.alpha||b.ia;this.d.x=a.x||0;this.d.y=a.y||0;this.d.t=a.text||"";this.d.ta=a.textAlign||b.ta;this.d.tb=a.ua||b.tb;this.type=T(this.d,"it");this.scale=T(this.d,"is");this.color=T(this.d,"ic");this.alpha=T(this.d,"ia");this.x=T(this.d,"x");this.y=T(this.d,"y");this.text=T(this.d,"t");this.textAlign=T(this.d,"ta");this.ua=T(this.d,"tb");this.la="is ic ia x y t ta tb".split(" ");
this.offset=new J(0,0);this.Q=n;this.Rb=0;this.M=[]}s=Ce.prototype;s.ub=function(){var a={};a.x=this.x()+this.offset.x;a.y=this.y()+this.offset.y;this.offset.x=0;this.offset.y=0;return a};function Od(a){a=a||{};return{type:a.it,scale:a.is,color:a.ic,alpha:a.ia,x:a.x,y:a.y,text:a.t,textAlign:a.ta,ua:a.tb}}s.Kb=function(a){this.offset.x=a.x;this.offset.y=a.y};s.mb=function(){var a={},b;for(b in this.d)a[b]=this.d[b];return a};s.yb=function(){var a=this,b={};H(this.la,function(c){b[c]=a.d[c]});return b};
s.Jb=function(a){var b=this;H(this.la,function(c){a[c]!==j&&(b.d[c]=a[c])})};
s.ga=function(a,b,c){if(!this.Q)return r;var d=this.scale(),e=this.textAlign(),f=new Vc(this.x(),this.y(),this.Q.x*this.scale(),this.Q.y*this.scale()),g=this.ua()||c?this.Rb:0;"c"==e?f.x-=f.f/2:"r"==e&&(f.x-=f.f);if(Math.abs(a-f.x-f.f/2)>f.f/2+g||Math.abs(b-f.y-f.k/2)>f.k/2+g)return r;if(this.ua()||c)return m;for(var g=c=0,i=this.M.length;g<i;g++)if(c=this.M[g].width*d,-1<c&&a>=f.x+("c"==e?f.f/2-c/2:"r"==e?f.f-c:0)&&a<=f.x+("c"==e?f.f/2+c/2:"r"==e?f.f:c)&&b>=f.y+this.M[g].top*d&&b<=f.y+(g+1<i?this.M[g+
1].top:this.M[g].top+this.M[g].size)*d)return m;return r};function De(a){this.c=a;this.padding=this.na=15;this.Q=this.S=this.R=n;this.canvas=document.createElement("CANVAS");this.canvas.style.position="absolute"}s=De.prototype;
s.N=function(a,b,c){var d,e,f,g=b===j;switch(this.c.textAlign()){case "c":a.textAlign="center";break;case "r":a.textAlign="right";break;default:a.textAlign="left"}a.textBaseline="top";a.fillStyle=this.c.color();a.strokeStyle=b||this.c.color();a.lineWidth=c||0;H(this.c.M,function(b){if(d!=b.size||e!=b.bold||f!=b.ab)d=b.size,e=b.bold,f=b.ab,a.font=Ge(b.ab,b.bold,b.size);g?a.fillText(b.text,0,b.top):a.strokeText(b.text,0,b.top)})};
function Ge(a,b,c){var d="";a&&(d+="italic ");b&&(d+="bold ");return d+c+"px Arial, Helvetica, sans-serif"}
s.Va=function(a){var a=a||1,b=a*this.c.scale(),c=Math.round(b*this.Q.x)+2*this.padding;Math.round(b*this.Q.y);switch(this.c.textAlign()){case "c":this.canvas.style.left=Math.round(a*(this.c.x()+this.c.offset.x)-c/2)+"px";break;case "r":this.canvas.style.left=Math.round(a*(this.c.x()+this.c.offset.x)-c+this.padding)+"px";break;default:this.canvas.style.left=Math.round(a*(this.c.x()+this.c.offset.x)-this.padding)+"px"}this.canvas.style.top=Math.round(a*(this.c.y()+this.c.offset.y)-this.padding)+"px"};
s.ka=function(a,b,c,d){this.padding=this.na*Math.max(1,b);var e=this.c,f=e.text().replace(/[\s\xa0]+$/,"").replace(/\n\r/g,"\n").replace(/\r/g,"\n").replace(/\t/g,"    ").split("\n"),g=0,i=[];H(f,function(a){i.push({text:a,top:g,size:12,width:-1,bold:r,ab:r});g+=18});e.M=i;var k=0;a.save();H(this.c.M,function(b){a.font=Ge(b.ab,b.bold,b.size);b.width=a.measureText(b.text).width;k=Math.min(2048,Math.max(b.width,k))});a.restore();this.Q=new J(k,this.c.M[this.c.M.length-1].top+this.c.M[this.c.M.length-
1].size);e=this.c;f=this.padding;e.Q=this.Q;e.Rb=f;e=Math.round(b*this.Q.x)+2*this.padding;f=Math.round(b*this.Q.y)+2*this.padding;d||(a.canvas.width=e,a.canvas.height=f,a.clearRect(0,0,e,f));a.save();if(d)switch(a.translate(this.c.x(),this.c.y()),this.c.textAlign()){case "c":a.translate(-e/2,-this.padding);break;case "r":a.translate(-e+this.padding,-this.padding);break;default:a.translate(-this.padding,-this.padding)}this.c.ua()&&(a.save(),a.fillStyle=Bc(this.c.color()),a.fillRect(0,0,e,f),a.restore());
c&&(a.save(),a.strokeStyle="rgba(255,0,0,0.75)",a.lineWidth=1,a.strokeRect(0.5,0.5,e-1,f-1),a.restore());switch(this.c.textAlign()){case "c":a.translate(e/2,this.padding);break;case "r":a.translate(e-this.padding,this.padding);break;default:a.translate(this.padding,this.padding)}a.scale(b,b);a.lineCap="round";this.c.ua()||(a.save(),this.N(a,Bc(this.c.color()),2/b),a.restore());this.N(a);a.restore()};
s.ha=function(a,b){var a=a||1,c=a*this.c.scale(),d={color:this.c.color(),alpha:this.c.alpha(),scale:c,selected:b,text:this.c.text(),textAlign:this.c.textAlign(),ua:this.c.ua()},e={x:this.c.x(),y:this.c.y(),Zb:this.c.offset.x,$b:this.c.offset.y,scale:c,textAlign:this.c.textAlign()};kd(d,this.R)||(this.R=d,d=this.canvas.getContext("2d"),this.ka(d,c,b));kd(e,this.S)||(this.S=e,this.Va(a))};s.Qa=function(a){a.save();this.ka(a,this.c.scale(),r,m);a.restore()};
s.Ja=function(){this.S=this.R=this.c=n;mb(this.canvas);this.canvas=n};function He(a){ye.call(this,a);this.c=a}B(He,ye);
He.prototype.N=function(a,b,c){var d=b===j,e=this.c.f(),f=this.c.k(),g=Math.min(e,f)/2;a.strokeStyle=b||this.c.color();a.lineWidth=c||this.c.lineWidth();a.beginPath();a.moveTo(e/2+g*Math.cos(0),f/2+g*Math.sin(0));a.arc(e/2,f/2,g,0,2*Math.PI,r);a.stroke();this.c.text()&&(a.font="12px Arial, Helvetica, sans-serif",a.textAlign="center",a.textBaseline="middle",d?(a.fillStyle=this.c.color(),a.fillText(this.c.text(),e/2,f/2)):(a.strokeStyle=b||this.c.color(),a.lineWidth=Math.min(2,(c||this.c.lineWidth())-
this.c.lineWidth()),a.strokeText(this.c.text(),e/2,f/2)))};function Ie(a,b){this.wa=a;this.cc=b;this.k=b.height;this.f=b.width;this.scale=1;this.G=[0.125,1/6,0.25,1/3,0.5,2/3,1,2,3,4,5,6,7,8,12,16];this.J=[];this.d={};this.d.is=1;this.d.ic="#ffff00";this.d.ia=1;this.d.nl=10;this.d.fl=10;this.d.lc=r;this.d.ta="l";this.d.tb=r;this.K=new re({D:[new J(0,0)]},this.d);this.J.push(this.K)}Ie.prototype.removeItem=function(a){Xa(this.J,a)};
Ie.prototype.getItem=function(a){var b=this.J,c;a:{c=function(b){return b.id==a};for(var d=b.length,e=u(b)?b.split(""):b,f=0;f<d;f++)if(f in e&&c.call(j,e[f])){c=f;break a}c=-1}return 0>c?n:u(b)?b.charAt(c):b[c]};function me(a,b){for(var c=a.J.length-1;0<=c&&!(a.J[c]!=a.K&&b(a.J[c])===m);c--);}function Je(a,b,c){for(var d=0,e=a.J.length;d<e&&!((c||a.J[d]!=a.K)&&b(a.J[d])===m);d++);}
Ie.prototype.Pb=function(){for(var a=0,b=this.G.length;a<b;a++)if(1E-6>=Math.abs(this.G[a]-this.scale)){this.scale=this.G[I(a-1,0,b-1)];break}else if(this.scale>this.G[a]&&(!this.G[a+1]||this.scale<this.G[a+1])){this.scale=this.G[a];break}};Ie.prototype.Ob=function(){for(var a=0,b=this.G.length;a<b;a++)if(1E-6>=Math.abs(this.G[a]-this.scale)){this.scale=this.G[I(a+1,0,b-1)];break}else if(this.scale>this.G[a]&&this.G[a+1]&&this.scale<this.G[a+1]){this.scale=this.G[a+1];break}};function Ke(a){ye.call(this,a);this.c=a}B(Ke,ye);Ke.prototype.N=function(a,b,c){a.strokeStyle=b||this.c.color();a.lineWidth=c||this.c.lineWidth();a.beginPath();a.moveTo(0,0);a.lineTo(this.c.f(),this.c.k());a.moveTo(this.c.f(),0);a.lineTo(0,this.c.k());a.stroke()};function Le(a){this.c=a;this.padding=this.na=10;this.S=this.R=n;this.canvas=document.createElement("canvas");this.canvas.width=2*this.padding;this.canvas.height=2*this.padding;this.canvas.style.position="absolute"}
function Me(a,b,c,d){var e=a.c.scale(),f=0<a.c.u();b.strokeStyle=c||a.c.color();b.lineWidth=d||a.c.lineWidth()*e;var g=f?new oe(b,a.c.A()*e,a.c.u()*e):b;g.beginPath();if(a.c.Xa()){var i=a.c.D(),k=i.length;H(i,function(a,b){if(0===b)g.moveTo(a.x,a.y);else{var c=i[b-1];1==b?g.lineTo((a.x+c.x)/2,(a.y+c.y)/2):g.quadraticCurveTo(c.x,c.y,(a.x+c.x)/2,(a.y+c.y)/2);b==k-1&&g.lineTo(a.x,a.y)}})}else H(a.c.D(),function(a,b){0===b?g.moveTo(a.x,a.y):g.lineTo(a.x,a.y)});g.stroke();f&&g.Ja()}s=Le.prototype;
s.N=function(a,b,c){var d=this.c.scale();a.save();a.lineCap="round";c?(a.save(),Me(this,a,"rgba(255,0,0,0.75)",this.c.lineWidth()*d+4/b)):(a.save(),Me(this,a,Bc(this.c.color()),this.c.lineWidth()*d+2/b));a.restore();Me(this,a);a.restore()};s.Va=function(a){a=a||1;this.canvas.style.left=Math.round(a*(this.c.offset.x+this.c.P.x)-this.padding)+"px";this.canvas.style.top=Math.round(a*(this.c.offset.y+this.c.P.y)-this.padding)+"px"};
s.ka=function(a,b,c,d,e){this.padding=this.na*Math.max(1,this.c.scale()*b);var f=this.c;if(0===f.D().length)f.P=n;else{var g=Number.MAX_VALUE,i=-Number.MAX_VALUE,k=Number.MAX_VALUE,l=-Number.MAX_VALUE;H(f.D(),function(a){g=Math.min(g,a.x);i=Math.max(i,a.x);k=Math.min(k,a.y);l=Math.max(l,a.y)});f.P=new Vc(g,k,i-g,l-k)}se(this.c);var f=Math.round(b*this.c.P.f)+2*this.padding,p=Math.round(b*this.c.P.k)+2*this.padding;e||(a.canvas.width=f,a.canvas.height=p,a.clearRect(0,0,f,p));a.save();e||a.translate(this.padding-
Math.round(b*this.c.P.x),this.padding-Math.round(b*this.c.P.y));a.scale(b,b);this.N(a,b,c);if(c&&d==Dd){var q=b,q=q||1,v=this.c.color(),y=Bc(v),w=7/q;a.save();H(this.c.D(),function(b){a.beginPath();a.moveTo(b.x+w,b.y);a.arc(b.x,b.y,w,0,2*Math.PI,r);a.strokeStyle=y;a.lineWidth=6/q;a.stroke();a.strokeStyle=v;a.lineWidth=4/q;a.stroke()});a.restore()}a.restore()};
s.ha=function(a,b,c){var a=a||1,d=this.c.mb();d.scale=a;d.selected=!!b;d.mode=c||n;kd(d,this.R)||(this.R=d,d=this.canvas.getContext("2d"),this.ka(d,a,b,c));b={Zb:this.c.offset.x,$b:this.c.offset.y,x:this.c.P.x,y:this.c.P.y,f:this.c.P.f,k:this.c.P.k,scale:a*this.c.scale()};kd(b,this.S)||(this.S=b,this.Va(a))};s.Qa=function(a){a.save();this.ka(a,1,r,n,m);a.restore()};s.Ja=function(){this.S=this.R=this.c=n;mb(this.canvas);this.canvas=n};function Ne(a,b){this.wa=a;this.c=b;this.Ib=1;this.Eb=m;this.fb=r;this.j=lb("DIV","canvas-container");this.j.appendChild(this.c.cc);this.fc=lb("DIV","fullsize");this.j.appendChild(this.fc);this.Da={};setInterval(A(this.Vb,this),10);Qc(O,W,A(this.Dc,this))}Ne.prototype.Dc=function(a){this.Eb=m;a&&this.Vb()};Ne.prototype.Vb=function(){this.Eb&&this.ha(this.c.scale);this.Eb=r};
Ne.prototype.ha=function(a){var b=this,c={};Je(this.c,function(d){a:{var e=a,e=e||1,f=b.Da[d.id];if(!f){switch(d.type()){case xd:f=new Ke(d);break;case yd:f=new Be(d);break;case zd:f=new Ae(d);break;case Ad:f=new He(d);break;case 5:f=new De(d);break;case 0:f=new Le(d)}if(!f)break a;b.Da[d.id]=f;b.fc.appendChild(f.canvas)}f.ha(e,b.wa.selected==d.id,b.wa.mode.id)}c[d.id]=m},m);for(var d in this.Da)c[d]||(this.Da[d].Ja(),delete this.Da[d]);if(this.c.scale!=this.Ib||this.fb){ob(this.j,{width:Math.round(this.c.scale*
this.c.f)+"px",height:Math.round(this.c.scale*this.c.k)+"px"});if(this.fb)d=this.wa,d.offset.x=Math.round(d.C.H/2-d.c.f*d.c.scale/2),d.offset.y=Math.round(d.C.L/2-d.c.k*d.c.scale/2),this.fb=r;else{d=this.wa;var e=this.c.scale/this.Ib,f=e*(d.C.L/2-d.offset.y),g=d.c.f*d.c.scale,i=d.c.k*d.c.scale;d.offset.x=-Math.round(e*(d.C.H/2-d.offset.x)-d.C.H/2);d.offset.y=-Math.round(f-d.C.L/2);d.offset.x=g<=d.C.H?Math.round(d.C.H/2-g/2):I(d.offset.x,d.C.H-g,0);d.offset.y=i<=d.C.L?Math.round(d.C.L/2-i/2):I(d.offset.y,
d.C.L-i,0)}this.j.style.left=this.wa.offset.x+"px";this.j.style.top=this.wa.offset.y+"px"}this.Ib=this.c.scale};Ne.prototype.Qa=function(a){var b=this;Je(this.c,function(c){b.Da[c.id]&&b.Da[c.id].Qa(a)})};function Oe(a,b){Y.call(this,a,b);this.Aa=this.Z=this.B=this.F=n}B(Oe,Y);s=Oe.prototype;s.Gb=function(){var a=this;Wa(od(this.canvas),function(b){return 0==b.type()?(a.B=b,O.i(W),m):r})};s.Oa=function(){this.Aa=this.Z=this.B=this.F=n;O.i(W)};s.qa=function(a,b){this.F&&this.za(a,b);if(this.B){var c=this;Wa(this.B.D(),function(a){var e=b.x-a.x,f=b.y-a.y;return 100>e*e+f*f?(c.Z=a,c.Aa=a.clone(),m):r});this.Z?this.F=b:O.i(U,vd)}};
s.ya=function(a,b){this.F&&(this.B&&this.Z)&&(this.Z.x=this.Aa.x+b.x-this.F.x,this.Z.y=this.Aa.y+b.y-this.F.y,se(this.B),O.i(W))};s.za=function(a,b){this.ya(a,b);if(this.F&&this.B&&this.Z){var c=[];H(this.B.D(),function(a){c.push(a.clone())});this.Z.x=this.Aa.x;this.Z.y=this.Aa.y;var d={id:this.B.id};d.cp=c;R(this.canvas,new Q(4,d))}this.Aa=this.Z=this.F=n};s.Ma=function(a){if(13==a.keyCode)return O.i(U,vd),m};function Pe(a,b){Y.call(this,a,b);this.Ea=n}B(Pe,Y);Pe.prototype.Gb=function(a){this.Ea=z(a)?a:n};Pe.prototype.qa=function(a,b){this.Ea!==n&&R(this.canvas,new Q(1,{type:this.Ea,x:b.x,y:b.y}))};function Qe(a,b){Y.call(this,a,b)}B(Qe,Y);Qe.prototype.qa=function(a,b){var c=this;O.i(Hd,function(a){a&&R(c.canvas,new Q(3,{text:a,x:b.x,y:b.y}))},P("Enter some text"))};function Re(a,b){var c=this;this.C=a;this.c=new Ie(this,b);this.view=new Ne(this,this.c);this.offset=new J;this.selected=n;md=this;this.pa={};this.pa[vd]=new ke(this,vd);this.pa[wd]=new ue(this,wd,this.c.K);this.pa[V]=new Pe(this,V);this.pa[Bd]=new Qe(this,Bd);this.pa[Dd]=new Oe(this,Dd);var d=n;Qc(O,U,function(a,b){if(c.pa[a]){var g=c.mode!=c.pa[a]||d!=b;g&&(c.mode&&c.mode.Oa)&&c.mode.Oa();c.mode=c.pa[a];g&&c.mode.Gb&&c.mode.Gb(b);d=b}});this.mode=n;this.Ua=[];this.Pa=[];this.Ha=0;this.rb=[];setInterval(function(){qd(c)},
100)}function qd(a){a.Ha=Math.max(0,a.Ha-1);0==a.Ha&&0<a.rb.length&&(a.Ua.unshift(a.rb),a.Pa=[],a.rb=[])}function Ue(a,b){var c=b.clientX,d=b.clientY,e=tb(a.C.fa.viewport);return new J(Math.round((c-e.x-a.offset.x)/a.c.scale),Math.round((d-e.y-a.offset.y)/a.c.scale))}function Ld(a){if(0!==a.Pa.length){var b=[];H(a.Pa[0],function(c){c=ld(c);c!=n&&(c.Bb=m,c.Cb=r,b.unshift(c),R(a,c))});a.Pa.shift();a.Ua.unshift(b)}}
function R(a,b){var c;switch(b.type){case 1:switch(b.q.type){case xd:c=new je(b.q,a.c.d);break;case yd:c=new ne(b.q,a.c.d);break;case zd:c=new ze(b.q,a.c.d);break;case Ad:c=new xe(b.q,a.c.d)}if(c)b.q.id=c.id,a.c.J.push(c);else return;break;case 2:if(b.q.D&&1<b.q.D.length)c=new re(b.q,a.c.d),b.q.id=c.id,a.c.J.push(c);else return;break;case 3:if(b.q.text)c=new Ce(b.q,a.c.d),b.q.id=c.id,a.c.J.push(c);else return;break;case 4:if(c=a.c.getItem(b.q.id)){if(!b.Fb){var d=c.yb(),e={id:b.q.id},f;for(f in b.q)d[f]!==
j&&(e[f]=d[f]);b.Fb=e}c.Jb(b.q)}else return;break;case 5:case 7:case 6:if(c=a.c.getItem(b.q.id))a.c.removeItem(c);else return;break;default:return}a.Ha++;!b.Cb&&!b.Bb&&a.rb.unshift(b);qd(a);O.i(W);O.i(Fd)}function od(a){return!a.selected?[]:(a=a.c.getItem(a.selected))?[a]:[]}s=Re.prototype;s.qa=function(a){this.mode.qa(a,Ue(this,a))};s.ya=function(a){this.mode.ya(a,Ue(this,a))};s.za=function(a){this.mode.za(a,Ue(this,a))};s.Za=function(a){this.mode.Za(a,Ue(this,a))};s.Ma=function(a){return this.mode.Ma(a)};
s.Pb=function(){O.i(W);this.c.Pb()};s.Ob=function(){O.i(W);this.c.Ob()};s.zb=function(a,b){O.i(W,m);var c=document.createElement("CANVAS"),d=c.getContext("2d"),b=a&&b&&"jpg"==b.toLowerCase()?"jpeg":"png";c.width=this.c.f;c.height=this.c.k;a&&d.drawImage(this.c.cc,0,0);this.view.Qa(d);try{return c.toDataURL("image/"+b)}catch(e){return alert("Source image must be from the same domain to be included in getImage. Try getImage() without any parameters."),""}};function Ve(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}h(Error("Invalid JSON string: "+a))}function We(a){this.lb=a}We.prototype.serialize=function(a){var b=[];Xe(this,a,b);return b.join("")};
function Xe(a,b,c){switch(typeof b){case "string":Ye(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==n){c.push("null");break}if(da(b)){a.serializeArray(b,c);break}c.push("{");var d="",e;for(e in b)if(Object.prototype.hasOwnProperty.call(b,e)){var f=b[e];"function"!=typeof f&&(c.push(d),Ye(e,c),c.push(":"),Xe(a,a.lb?a.lb.call(b,e,f):f,c),d=",")}c.push("}");break;case "function":break;default:h(Error("Unknown type: "+
typeof b))}}var Ze={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},$e=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function Ye(a,b){b.push('"',a.replace($e,function(a){if(a in Ze)return Ze[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Ze[a]=e+b.toString(16)}),'"')}
We.prototype.serializeArray=function(a,b){var c=a.length;b.push("[");for(var d="",e=0;e<c;e++)b.push(d),d=a[e],Xe(this,this.lb?this.lb.call(a,String(e),d):d,b),d=",";b.push("]")};function af(a,b){var c=this,b=b||{};this.q={f:b.width||n,k:b.height||n,zoom:b.zoom||"contain",parent:b.parent||n,ra:b.onChange||n};this.minWidth=556;this.nb=a;var d=document.createElement("img");this.Cc=M(d,"load",function(){c.ba(d)});d.src=this.nb.src;b.ra&&Qc(O,Fd,function(){b.ra()})}
af.prototype.ba=function(a){ce(this.Cc);this.m=new Re(this,a);this.fa=new Gd(this);this.H=this.q.f||a.width;this.L=this.q.k||a.height;z(this.H)&&this.H<this.minWidth&&(this.H=this.minWidth);ob(this.fa.va,{position:"relative",display:"inherit"==this.nb.style.display?"inline-block":this.nb.style.display||"inline-block",width:z(this.H)?this.H+"px":this.H,height:z(this.L)?this.L+29+"px":this.L});if(this.q.parent)this.q.parent.appendChild(this.fa.va);else{var a=this.nb,b=a.parentNode;b&&b.replaceChild(this.fa.va,
a)}z(this.H)||(this.H=(new $a(this.fa.va.offsetWidth,this.fa.va.offsetHeight)).width-2);z(this.L)||(this.L=(new $a(this.fa.va.offsetWidth,this.fa.va.offsetHeight)).height-29-2);this.fa.ba();b=this.m;a=this.q.zoom;a=z(a)?a/100:"cover"==a?Math.max(b.C.H/b.c.f,b.C.L/b.c.k):Math.min(b.C.H/b.c.f,b.C.L/b.c.k);b=b.c;b.scale=I(a,b.G[0],b.G[b.G.length-1]);O.i(W);this.m.view.fb=m};
af.prototype.Hc=function(a){var b=this,c=this.m.c;c.J=[];c.J.push(c.K);H(a.items||[],function(a){var c=n;switch(a.it){case xd:c=new je(Md(a),b.m.c.d);break;case yd:c=new ne(Md(a),b.m.c.d);break;case zd:c=new ze(Md(a),b.m.c.d);break;case Ad:c=new xe(Md(a),b.m.c.d);break;case 0:c=new re(Nd(a),b.m.c.d);break;case 5:c=new Ce(Od(a),b.m.c.d)}c&&b.m.c.J.push(c)});O.i(W)};
af.prototype.getData=function(a){var b=[];Je(this.m.c,function(a){b.push(a.mb())});if(a){a=(new We(j)).serialize({items:b});a=String(a);if(a.quote)a=a.quote();else{for(var c=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),g=c,i=d+1,k;if(!(k=ta[e])){if(!(31<f&&127>f))if(e in ua)e=ua[e];else if(e in ta)e=ua[e]=ta[e];else{f=e;k=e.charCodeAt(0);if(31<k&&127>k)f=e;else{if(256>k){if(f="\\x",16>k||256<k)f+="0"}else f="\\u",4096>k&&(f+="0");f+=k.toString(16).toUpperCase()}e=ua[e]=f}k=e}g[i]=
k}c.push('"');a=c.join("")}a:for(c=0;1>c;c++)if('"'==a.charAt(0)&&'"'==a.charAt(a.length-1)){a=a.substring(1,a.length-1);break a}}else a=(new We(j)).serialize({items:b});return a};af.prototype.zb=function(a,b){return this.m.zb(a,b)};var O=new Rd,W="cr",Ed="sc",id="scp",Hd="sta",Rc="ho",U="m",Fd="a",vd=0,wd=1,V=2,Bd=3,Dd=4;
ba("BetaCreator",function(a,b){var c=new af(a,b),d=b.onError||function(a){alert(a)};return{loadData:function(a){try{a=Ve(a),c.Hc(a)}catch(b){d(P("Invalid data."))}},getData:function(a){return c.getData(a)},getImage:function(a,b){return c.zb(a,b)}}});})();
